// Code generated by scalr-gen. DO NOT EDIT.

package run_trigger

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to RunTrigger operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new RunTrigger client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Create a new run trigger. In order to create a run trigger, the user must have `workspaces:read` permission for the upstream workspace and permissions `workspaces:update` and `runs:create` for the downstream workspace.
func (c *Client) CreateRunTriggerRaw(ctx context.Context, req *schemas.RunTriggerRequest) (*http.Response, error) {
	path := "/run-triggers"

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// Create a new run trigger. In order to create a run trigger, the user must have `workspaces:read` permission for the upstream workspace and permissions `workspaces:update` and `runs:create` for the downstream workspace.
func (c *Client) CreateRunTrigger(ctx context.Context, req *schemas.RunTriggerRequest) (*schemas.RunTrigger, *client.Response, error) {
	httpResp, err := c.CreateRunTriggerRaw(ctx, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.RunTrigger       `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

func (c *Client) DeleteRunTriggerRaw(ctx context.Context, runTrigger string) (*http.Response, error) {
	path := "/run-triggers/{run_trigger}"
	path = strings.ReplaceAll(path, "{run_trigger}", url.PathEscape(runTrigger))

	return c.httpClient.Delete(ctx, path, nil, nil)
}

func (c *Client) DeleteRunTrigger(ctx context.Context, runTrigger string) (*client.Response, error) {
	httpResp, err := c.DeleteRunTriggerRaw(ctx, runTrigger)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Show details of a specific trigger.
func (c *Client) GetRunTriggerRaw(ctx context.Context, runTrigger string, opts *GetRunTriggerOptions) (*http.Response, error) {
	path := "/run-triggers/{run_trigger}"
	path = strings.ReplaceAll(path, "{run_trigger}", url.PathEscape(runTrigger))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific trigger.
func (c *Client) GetRunTrigger(ctx context.Context, runTrigger string, opts *GetRunTriggerOptions) (*schemas.RunTrigger, *client.Response, error) {
	httpResp, err := c.GetRunTriggerRaw(ctx, runTrigger, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.RunTrigger       `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetRunTriggerOptions holds optional parameters for GetRunTrigger
type GetRunTriggerOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}
