// Code generated by scalr-gen. DO NOT EDIT.

package vcs_provider

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to VcsProvider operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new VcsProvider client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Create a new VCS connection between Scalr and a VCS provider. VCS providers can be created at the Scalr account. Self-hosted Scalr also supports the creation of global VCS providers. If a VCS provider is created globally, all accounts within the self-hosted installation will have access to use the VCS provider. Only VCS providers with `personal_token` auth type, can be created through the API. If you need to set up `oauth2` provider, you should use Scalr [web interface](/docs/github) to do this.
func (c *Client) CreateVcsProviderRaw(ctx context.Context, req *schemas.VcsProviderRequest) (*http.Response, error) {
	path := "/vcs-providers"

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// Create a new VCS connection between Scalr and a VCS provider. VCS providers can be created at the Scalr account. Self-hosted Scalr also supports the creation of global VCS providers. If a VCS provider is created globally, all accounts within the self-hosted installation will have access to use the VCS provider. Only VCS providers with `personal_token` auth type, can be created through the API. If you need to set up `oauth2` provider, you should use Scalr [web interface](/docs/github) to do this.
func (c *Client) CreateVcsProvider(ctx context.Context, req *schemas.VcsProviderRequest) (*schemas.VcsProvider, *client.Response, error) {
	httpResp, err := c.CreateVcsProviderRaw(ctx, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.VcsProvider      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// The endpoint deletes a VCS provider by ID.
func (c *Client) DeleteVcsProviderRaw(ctx context.Context, vcsProvider string) (*http.Response, error) {
	path := "/vcs-providers/{vcs_provider}"
	path = strings.ReplaceAll(path, "{vcs_provider}", url.PathEscape(vcsProvider))

	return c.httpClient.Delete(ctx, path, nil, nil)
}

// The endpoint deletes a VCS provider by ID.
func (c *Client) DeleteVcsProvider(ctx context.Context, vcsProvider string) (*client.Response, error) {
	httpResp, err := c.DeleteVcsProviderRaw(ctx, vcsProvider)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Show details of a specific VCS provider.
func (c *Client) GetVcsProviderRaw(ctx context.Context, vcsProvider string, opts *GetVcsProviderOptions) (*http.Response, error) {
	path := "/vcs-providers/{vcs_provider}"
	path = strings.ReplaceAll(path, "{vcs_provider}", url.PathEscape(vcsProvider))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific VCS provider.
func (c *Client) GetVcsProvider(ctx context.Context, vcsProvider string, opts *GetVcsProviderOptions) (*schemas.VcsProvider, *client.Response, error) {
	httpResp, err := c.GetVcsProviderRaw(ctx, vcsProvider, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.VcsProvider      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetVcsProviderOptions holds optional parameters for GetVcsProvider
type GetVcsProviderOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}

// This endpoint returns a list of VCS providers by various filters. To list VCS providers accessible from a specific environment - `filter[environment]`, or when from a specific account - `filter[account]` has to be specified. For self-hosted Scalr there's also an option to list all VCS providers created globally - both `filter[account]=null` and `filter[environment]=null` has to be specified. If no `environment` or `account` filters were specified, all VCS providers to which a current user has read access will be returned.
func (c *Client) ListVcsProvidersRaw(ctx context.Context, opts *ListVcsProvidersOptions) (*http.Response, error) {
	path := "/vcs-providers"

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint returns a list of VCS providers by various filters. To list VCS providers accessible from a specific environment - `filter[environment]`, or when from a specific account - `filter[account]` has to be specified. For self-hosted Scalr there's also an option to list all VCS providers created globally - both `filter[account]=null` and `filter[environment]=null` has to be specified. If no `environment` or `account` filters were specified, all VCS providers to which a current user has read access will be returned.
func (c *Client) ListVcsProviders(ctx context.Context, opts *ListVcsProvidersOptions) ([]*schemas.VcsProvider, *client.Response, error) {
	httpResp, err := c.ListVcsProvidersRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.VcsProvider `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.VcsProvider, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListVcsProvidersIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.VcsProvider.ListVcsProvidersIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListVcsProvidersIter(ctx context.Context, opts *ListVcsProvidersOptions) iter.Seq2[schemas.VcsProvider, error] {
	return func(yield func(schemas.VcsProvider, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.VcsProvider{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListVcsProvidersOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListVcsProviders(ctx, pageOpts)
			if err != nil {
				yield(schemas.VcsProvider{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListVcsProvidersPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.VcsProvider.ListVcsProvidersPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListVcsProvidersPaged(ctx context.Context, opts *ListVcsProvidersOptions) *client.Iterator[schemas.VcsProvider] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.VcsProvider, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListVcsProvidersOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListVcsProviders(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.VcsProvider](ctx, pageSize, fetchPage)
}

// ListVcsProvidersOptions holds optional parameters for ListVcsProviders
type ListVcsProvidersOptions struct {
	// Full text search based on a VCS provider's `name`
	Query string
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort []string
	// The comma-separated list of relationship paths.
	Include []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}

// This endpoint allows updates to attributes of an existing VCS provider.
func (c *Client) UpdateVcsProviderRaw(ctx context.Context, vcsProvider string, req *schemas.VcsProviderRequest) (*http.Response, error) {
	path := "/vcs-providers/{vcs_provider}"
	path = strings.ReplaceAll(path, "{vcs_provider}", url.PathEscape(vcsProvider))

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Patch(ctx, path, body, nil)
}

// This endpoint allows updates to attributes of an existing VCS provider.
func (c *Client) UpdateVcsProvider(ctx context.Context, vcsProvider string, req *schemas.VcsProviderRequest) (*schemas.VcsProvider, *client.Response, error) {
	httpResp, err := c.UpdateVcsProviderRaw(ctx, vcsProvider, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.VcsProvider      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}
