// Code generated by scalr-gen. DO NOT EDIT.

package agent_pool

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to AgentPool operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new AgentPool client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Create a new [agent pool](/docs/agent-pools) resource. Agent pools can be created at the `account` or `environment` scope. The scope must be defined as part of the agent pool creation. If a pool is created at the account scope, all environments and workspaces within those environments will have access to use the pool. If a pool is created at the environment scope, then only the workspaces in that environment can use that pool. The typical flow for configuring a new agent pool involves the following operations: * Create an agent pool * [Create an access token](create_agent_pool_token) for the pool. The pool token is needed by an agent in order to join the agent pool. During the agent<->server handshake phase, the API server will generate a unique session token for each agent which will be used for all communication with the API server. * Install/Configure an agent on the customer's network.
func (c *Client) CreateAgentPoolRaw(ctx context.Context, req *schemas.AgentPoolRequest, opts *CreateAgentPoolOptions) (*http.Response, error) {
	path := "/agent-pools"

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// Create a new [agent pool](/docs/agent-pools) resource. Agent pools can be created at the `account` or `environment` scope. The scope must be defined as part of the agent pool creation. If a pool is created at the account scope, all environments and workspaces within those environments will have access to use the pool. If a pool is created at the environment scope, then only the workspaces in that environment can use that pool. The typical flow for configuring a new agent pool involves the following operations: * Create an agent pool * [Create an access token](create_agent_pool_token) for the pool. The pool token is needed by an agent in order to join the agent pool. During the agent<->server handshake phase, the API server will generate a unique session token for each agent which will be used for all communication with the API server. * Install/Configure an agent on the customer's network.
func (c *Client) CreateAgentPool(ctx context.Context, req *schemas.AgentPoolRequest, opts *CreateAgentPoolOptions) (*schemas.AgentPool, *client.Response, error) {
	httpResp, err := c.CreateAgentPoolRaw(ctx, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AgentPool        `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// CreateAgentPoolOptions holds optional parameters for CreateAgentPool
type CreateAgentPoolOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint deletes an [agent pool](/docs/agent-pools) by ID.
func (c *Client) DeleteAgentPoolRaw(ctx context.Context, agentPool string) (*http.Response, error) {
	path := "/agent-pools/{agent_pool}"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	return c.httpClient.Delete(ctx, path, nil)
}

// This endpoint deletes an [agent pool](/docs/agent-pools) by ID.
func (c *Client) DeleteAgentPool(ctx context.Context, agentPool string) (*client.Response, error) {
	httpResp, err := c.DeleteAgentPoolRaw(ctx, agentPool)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Show details of a specific [agent pool](/docs/agent-pools).
func (c *Client) GetAgentPoolRaw(ctx context.Context, agentPool string, opts *GetAgentPoolOptions) (*http.Response, error) {
	path := "/agent-pools/{agent_pool}"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific [agent pool](/docs/agent-pools).
func (c *Client) GetAgentPool(ctx context.Context, agentPool string, opts *GetAgentPoolOptions) (*schemas.AgentPool, *client.Response, error) {
	httpResp, err := c.GetAgentPoolRaw(ctx, agentPool, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AgentPool        `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetAgentPoolOptions holds optional parameters for GetAgentPool
type GetAgentPoolOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint returns a list of [agent pools](/docs/agent-pools) by various filters.
func (c *Client) GetAgentPoolsRaw(ctx context.Context, opts *GetAgentPoolsOptions) (*http.Response, error) {
	path := "/agent-pools"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint returns a list of [agent pools](/docs/agent-pools) by various filters.
func (c *Client) GetAgentPools(ctx context.Context, opts *GetAgentPoolsOptions) ([]*schemas.AgentPool, *client.Response, error) {
	httpResp, err := c.GetAgentPoolsRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.AgentPool `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.AgentPool, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// GetAgentPoolsIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.AgentPool.GetAgentPoolsIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) GetAgentPoolsIter(ctx context.Context, opts *GetAgentPoolsOptions) iter.Seq2[schemas.AgentPool, error] {
	return func(yield func(schemas.AgentPool, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.AgentPool{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &GetAgentPoolsOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.GetAgentPools(ctx, pageOpts)
			if err != nil {
				yield(schemas.AgentPool{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// GetAgentPoolsPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.AgentPool.GetAgentPoolsPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) GetAgentPoolsPaged(ctx context.Context, opts *GetAgentPoolsOptions) *client.Iterator[schemas.AgentPool] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.AgentPool, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &GetAgentPoolsOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.GetAgentPools(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.AgentPool](ctx, pageSize, fetchPage)
}

// GetAgentPoolsOptions holds optional parameters for GetAgentPools
type GetAgentPoolsOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of relationship paths.
	Include []string
	// The comma-separated list of attributes.
	Sort   []string
	Filter map[string]string
}

// This endpoint updates an [agent pool](/docs/agent-pools) by ID.
func (c *Client) UpdateAgentPoolRaw(ctx context.Context, agentPool string, req *schemas.AgentPoolRequest, opts *UpdateAgentPoolOptions) (*http.Response, error) {
	path := "/agent-pools/{agent_pool}"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Patch(ctx, path, body, nil)
}

// This endpoint updates an [agent pool](/docs/agent-pools) by ID.
func (c *Client) UpdateAgentPool(ctx context.Context, agentPool string, req *schemas.AgentPoolRequest, opts *UpdateAgentPoolOptions) (*schemas.AgentPool, *client.Response, error) {
	httpResp, err := c.UpdateAgentPoolRaw(ctx, agentPool, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AgentPool        `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// UpdateAgentPoolOptions holds optional parameters for UpdateAgentPool
type UpdateAgentPoolOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}
