// Code generated by scalr-gen. DO NOT EDIT.

package policy_check

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to PolicyCheck operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new PolicyCheck client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Show details of a specific Terraform policy check stage.
func (c *Client) GetPolicyCheckRaw(ctx context.Context, policyCheck string) (*http.Response, error) {
	path := "/policy-checks/{policy_check}"
	path = strings.ReplaceAll(path, "{policy_check}", url.PathEscape(policyCheck))

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific Terraform policy check stage.
func (c *Client) GetPolicyCheck(ctx context.Context, policyCheck string) (*schemas.PolicyCheck, *client.Response, error) {
	httpResp, err := c.GetPolicyCheckRaw(ctx, policyCheck)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.PolicyCheck      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	return &result.Data, resp, nil
}

// Download the raw output of the OPA policy check stage.
func (c *Client) GetPolicyChecksLogRaw(ctx context.Context, policyCheck string, opts *GetPolicyChecksLogOptions) (*http.Response, error) {
	path := "/policy-checks/{policy_check}/output"
	path = strings.ReplaceAll(path, "{policy_check}", url.PathEscape(policyCheck))

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Clean (bool)
		params.Set("clean", fmt.Sprintf("%t", opts.Clean))
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Download the raw output of the OPA policy check stage.
func (c *Client) GetPolicyChecksLog(ctx context.Context, policyCheck string, opts *GetPolicyChecksLogOptions) (*client.Response, error) {
	httpResp, err := c.GetPolicyChecksLogRaw(ctx, policyCheck, opts)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// GetPolicyChecksLogOptions holds optional parameters for GetPolicyChecksLog
type GetPolicyChecksLogOptions struct {
	// Strip ANSI escape codes.
	Clean  bool
	Filter map[string]string
}

// List policy checks for a specific run.
func (c *Client) ListPolicyChecksRaw(ctx context.Context, run string) (*http.Response, error) {
	path := "/runs/{run}/policy-checks"
	path = strings.ReplaceAll(path, "{run}", url.PathEscape(run))

	return c.httpClient.Get(ctx, path, nil)
}

// List policy checks for a specific run.
func (c *Client) ListPolicyChecks(ctx context.Context, run string) ([]*schemas.PolicyCheck, *client.Response, error) {
	httpResp, err := c.ListPolicyChecksRaw(ctx, run)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.PolicyCheck `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.PolicyCheck, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// This endpoint overrides a soft-mandatory policy.
func (c *Client) OverridePolicyRaw(ctx context.Context, policyCheck string) (*http.Response, error) {
	path := "/policy-checks/{policy_check}/actions/override"
	path = strings.ReplaceAll(path, "{policy_check}", url.PathEscape(policyCheck))

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint overrides a soft-mandatory policy.
func (c *Client) OverridePolicy(ctx context.Context, policyCheck string) (*schemas.PolicyCheck, *client.Response, error) {
	httpResp, err := c.OverridePolicyRaw(ctx, policyCheck)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.PolicyCheck      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	return &result.Data, resp, nil
}
