// Code generated by scalr-gen. DO NOT EDIT.

package terraform_resource_usage

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to TerraformResourceUsage operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new TerraformResourceUsage client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint returns instance of resource usage.
func (c *Client) GetResourceUsageRaw(ctx context.Context, resourceUsage string, opts *GetResourceUsageOptions) (*http.Response, error) {
	path := "/reports/resources/{resource_usage}"
	path = strings.ReplaceAll(path, "{resource_usage}", url.PathEscape(resourceUsage))

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint returns instance of resource usage.
func (c *Client) GetResourceUsage(ctx context.Context, resourceUsage string, opts *GetResourceUsageOptions) (*schemas.TerraformResourceUsage, *client.Response, error) {
	httpResp, err := c.GetResourceUsageRaw(ctx, resourceUsage, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.TerraformResourceUsage `json:"data"`
		Included []map[string]interface{}       `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetResourceUsageOptions holds optional parameters for GetResourceUsage
type GetResourceUsageOptions struct {
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}

// This endpoint lists unique terraform resource provider types.
func (c *Client) ListTerraformResourceProvidersRaw(ctx context.Context, opts *ListTerraformResourceProvidersOptions) (*http.Response, error) {
	path := "/reports/resource-providers"

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists unique terraform resource provider types.
func (c *Client) ListTerraformResourceProviders(ctx context.Context, opts *ListTerraformResourceProvidersOptions) (string, *client.Response, error) {
	httpResp, err := c.ListTerraformResourceProvidersRaw(ctx, opts)
	if err != nil {
		return "", nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	bodyBytes, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return "", resp, fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), resp, nil
}

// ListTerraformResourceProvidersOptions holds optional parameters for ListTerraformResourceProviders
type ListTerraformResourceProvidersOptions struct {
	// Query string
	Query  string
	Filter map[string]string
}

// This endpoint lists terraform resource usages.
func (c *Client) ListTerraformResourceUsagesRaw(ctx context.Context, opts *ListTerraformResourceUsagesOptions) (*http.Response, error) {
	path := "/reports/resources"

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		// Handle parameter: Format (string)
		if opts.Format != "" {
			params.Set("format", opts.Format)
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists terraform resource usages.
func (c *Client) ListTerraformResourceUsages(ctx context.Context, opts *ListTerraformResourceUsagesOptions) ([]*schemas.TerraformResourceUsage, *client.Response, error) {
	httpResp, err := c.ListTerraformResourceUsagesRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.TerraformResourceUsage `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.TerraformResourceUsage, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListTerraformResourceUsagesIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.TerraformResourceUsage.ListTerraformResourceUsagesIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListTerraformResourceUsagesIter(ctx context.Context, opts *ListTerraformResourceUsagesOptions) iter.Seq2[schemas.TerraformResourceUsage, error] {
	return func(yield func(schemas.TerraformResourceUsage, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.TerraformResourceUsage{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListTerraformResourceUsagesOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListTerraformResourceUsages(ctx, pageOpts)
			if err != nil {
				yield(schemas.TerraformResourceUsage{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListTerraformResourceUsagesPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.TerraformResourceUsage.ListTerraformResourceUsagesPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListTerraformResourceUsagesPaged(ctx context.Context, opts *ListTerraformResourceUsagesOptions) *client.Iterator[schemas.TerraformResourceUsage] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.TerraformResourceUsage, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListTerraformResourceUsagesOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListTerraformResourceUsages(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.TerraformResourceUsage](ctx, pageSize, fetchPage)
}

// ListTerraformResourceUsagesOptions holds optional parameters for ListTerraformResourceUsages
type ListTerraformResourceUsagesOptions struct {
	// The search string. Supports search by resource name.
	Query string
	// Page number.
	PageNumber int
	// Page size.
	PageSize int
	// Format of the response. It can be 'json' or 'csv'.
	Format string
	// The comma-separated list of attributes.
	Sort []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}
