// Code generated by scalr-gen. DO NOT EDIT.

package cost_estimate

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to CostEstimate operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new CostEstimate client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Show details of a specific Cost Estimate phase.
func (c *Client) GetCostEstimateRaw(ctx context.Context, costEstimate string) (*client.Response, error) {
	path := "/cost-estimates/{cost_estimate}"
	path = strings.ReplaceAll(path, "{cost_estimate}", url.PathEscape(costEstimate))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Show details of a specific Cost Estimate phase.
func (c *Client) GetCostEstimate(ctx context.Context, costEstimate string) (*schemas.CostEstimate, error) {
	resp, err := c.GetCostEstimateRaw(ctx, costEstimate)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.CostEstimate     `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &result.Data, nil
}

// This endpoint generates a temporary public URL, that can be used to download a [JSON formatted cost breakdown](https://www.infracost.io/docs/multi_project/report/#examples).
func (c *Client) GetCostEstimateBreakdownRaw(ctx context.Context, costEstimate string) (*client.Response, error) {
	path := "/cost-estimates/{cost_estimate}/breakdown"
	path = strings.ReplaceAll(path, "{cost_estimate}", url.PathEscape(costEstimate))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint generates a temporary public URL, that can be used to download a [JSON formatted cost breakdown](https://www.infracost.io/docs/multi_project/report/#examples).
func (c *Client) GetCostEstimateBreakdown(ctx context.Context, costEstimate string) error {
	resp, err := c.GetCostEstimateBreakdownRaw(ctx, costEstimate)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// This endpoint generates a temporary public URL, that can be used to download a raw `text/plan` output of the cost estimation.
func (c *Client) GetCostEstimateLogRaw(ctx context.Context, costEstimate string) (*client.Response, error) {
	path := "/cost-estimates/{cost_estimate}/output"
	path = strings.ReplaceAll(path, "{cost_estimate}", url.PathEscape(costEstimate))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint generates a temporary public URL, that can be used to download a raw `text/plan` output of the cost estimation.
func (c *Client) GetCostEstimateLog(ctx context.Context, costEstimate string) (string, error) {
	resp, err := c.GetCostEstimateLogRaw(ctx, costEstimate)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}
