// Code generated by scalr-gen. DO NOT EDIT.

package account

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to Account operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new Account client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint adds provided [users](users.html#the-user-resource) to those who can log in to the account via password, even when SSO is enforced.
func (c *Client) AddSsoBypassUsersRaw(ctx context.Context, account string, req []schemas.User) (*http.Response, error) {
	path := "/accounts/{account}/relationships/sso-bypass-users"
	path = strings.ReplaceAll(path, "{account}", url.PathEscape(account))

	// This is a relationship operation - convert resources to relationship identifiers
	relationshipData := make([]map[string]interface{}, len(req))
	for i, item := range req {
		relationshipData[i] = map[string]interface{}{
			"id":   item.GetID(),
			"type": item.GetResourceType(),
		}
	}
	body := map[string]interface{}{"data": relationshipData}
	return c.httpClient.Post(ctx, path, body, nil)
}

// This endpoint adds provided [users](users.html#the-user-resource) to those who can log in to the account via password, even when SSO is enforced.
func (c *Client) AddSsoBypassUsers(ctx context.Context, account string, req []schemas.User) (*client.Response, error) {
	httpResp, err := c.AddSsoBypassUsersRaw(ctx, account, req)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// This endpoint removes given [users](users.html#the-user-resource) from the list of those who can log in to the account via password, even when SSO is enforced.
func (c *Client) DeleteSsoBypassUsersRaw(ctx context.Context, account string, req []schemas.User) (*http.Response, error) {
	path := "/accounts/{account}/relationships/sso-bypass-users"
	path = strings.ReplaceAll(path, "{account}", url.PathEscape(account))

	// This is a relationship operation - convert resources to relationship identifiers
	relationshipData := make([]map[string]interface{}, len(req))
	for i, item := range req {
		relationshipData[i] = map[string]interface{}{
			"id":   item.GetID(),
			"type": item.GetResourceType(),
		}
	}
	body := map[string]interface{}{"data": relationshipData}
	return c.httpClient.Post(ctx, path, body, nil)
}

// This endpoint removes given [users](users.html#the-user-resource) from the list of those who can log in to the account via password, even when SSO is enforced.
func (c *Client) DeleteSsoBypassUsers(ctx context.Context, account string, req []schemas.User) (*client.Response, error) {
	httpResp, err := c.DeleteSsoBypassUsersRaw(ctx, account, req)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Show details of a specific account.
func (c *Client) GetAccountRaw(ctx context.Context, account string, opts *GetAccountOptions) (*http.Response, error) {
	path := "/accounts/{account}"
	path = strings.ReplaceAll(path, "{account}", url.PathEscape(account))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific account.
func (c *Client) GetAccount(ctx context.Context, account string, opts *GetAccountOptions) (*schemas.Account, *client.Response, error) {
	httpResp, err := c.GetAccountRaw(ctx, account, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.Account          `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetAccountOptions holds optional parameters for GetAccount
type GetAccountOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

func (c *Client) GetAccountsRaw(ctx context.Context, opts *GetAccountsOptions) (*http.Response, error) {
	path := "/accounts"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

func (c *Client) GetAccounts(ctx context.Context, opts *GetAccountsOptions) ([]*schemas.Account, *client.Response, error) {
	httpResp, err := c.GetAccountsRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.Account `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.Account, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// GetAccountsIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.Account.GetAccountsIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) GetAccountsIter(ctx context.Context, opts *GetAccountsOptions) iter.Seq2[schemas.Account, error] {
	return func(yield func(schemas.Account, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.Account{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &GetAccountsOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.GetAccounts(ctx, pageOpts)
			if err != nil {
				yield(schemas.Account{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// GetAccountsPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.Account.GetAccountsPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) GetAccountsPaged(ctx context.Context, opts *GetAccountsOptions) *client.Iterator[schemas.Account] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.Account, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &GetAccountsOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.GetAccounts(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.Account](ctx, pageSize, fetchPage)
}

// GetAccountsOptions holds optional parameters for GetAccounts
type GetAccountsOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of relationship paths.
	Include []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}

func (c *Client) GetMetricsRaw(ctx context.Context, account string) (*http.Response, error) {
	path := "/accounts/{account}/metrics"
	path = strings.ReplaceAll(path, "{account}", url.PathEscape(account))

	return c.httpClient.Get(ctx, path, nil)
}

func (c *Client) GetMetrics(ctx context.Context, account string) (string, *client.Response, error) {
	httpResp, err := c.GetMetricsRaw(ctx, account)
	if err != nil {
		return "", nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	bodyBytes, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return "", resp, fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), resp, nil
}

// This endpoint returns a list of [users](users.html#the-user-resource) who can log in to the account via password, even when SSO is enforced.
func (c *Client) ListSsoBypassUsersRaw(ctx context.Context, account string, opts *ListSsoBypassUsersOptions) (*http.Response, error) {
	path := "/accounts/{account}/relationships/sso-bypass-users"
	path = strings.ReplaceAll(path, "{account}", url.PathEscape(account))

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint returns a list of [users](users.html#the-user-resource) who can log in to the account via password, even when SSO is enforced.
func (c *Client) ListSsoBypassUsers(ctx context.Context, account string, opts *ListSsoBypassUsersOptions) ([]*schemas.User, *client.Response, error) {
	httpResp, err := c.ListSsoBypassUsersRaw(ctx, account, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.User `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.User, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListSsoBypassUsersIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.Account.ListSsoBypassUsersIter(ctx, account, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListSsoBypassUsersIter(ctx context.Context, account string, opts *ListSsoBypassUsersOptions) iter.Seq2[schemas.User, error] {
	return func(yield func(schemas.User, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.User{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListSsoBypassUsersOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListSsoBypassUsers(ctx, account, pageOpts)
			if err != nil {
				yield(schemas.User{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListSsoBypassUsersPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.Account.ListSsoBypassUsersPaged(ctx, account, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListSsoBypassUsersPaged(ctx context.Context, account string, opts *ListSsoBypassUsersOptions) *client.Iterator[schemas.User] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.User, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListSsoBypassUsersOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListSsoBypassUsers(ctx, account, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.User](ctx, pageSize, fetchPage)
}

// ListSsoBypassUsersOptions holds optional parameters for ListSsoBypassUsers
type ListSsoBypassUsersOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	Filter   map[string]string
}

// This endpoint completely replaces the list of [users](users.html#the-user-resource) who can log in to the account via password, even when SSO is enforced, with a provided list.
func (c *Client) ReplaceSsoBypassUsersRaw(ctx context.Context, account string, req []schemas.User) (*http.Response, error) {
	path := "/accounts/{account}/relationships/sso-bypass-users"
	path = strings.ReplaceAll(path, "{account}", url.PathEscape(account))

	// This is a relationship operation - convert resources to relationship identifiers
	relationshipData := make([]map[string]interface{}, len(req))
	for i, item := range req {
		relationshipData[i] = map[string]interface{}{
			"id":   item.GetID(),
			"type": item.GetResourceType(),
		}
	}
	body := map[string]interface{}{"data": relationshipData}
	return c.httpClient.Patch(ctx, path, body, nil)
}

// This endpoint completely replaces the list of [users](users.html#the-user-resource) who can log in to the account via password, even when SSO is enforced, with a provided list.
func (c *Client) ReplaceSsoBypassUsers(ctx context.Context, account string, req []schemas.User) (*client.Response, error) {
	httpResp, err := c.ReplaceSsoBypassUsersRaw(ctx, account, req)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

func (c *Client) UpdateAccountRaw(ctx context.Context, account string, req *schemas.AccountRequest) (*http.Response, error) {
	path := "/accounts/{account}"
	path = strings.ReplaceAll(path, "{account}", url.PathEscape(account))

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Patch(ctx, path, body, nil)
}

func (c *Client) UpdateAccount(ctx context.Context, account string, req *schemas.AccountRequest) (*schemas.Account, *client.Response, error) {
	httpResp, err := c.UpdateAccountRaw(ctx, account, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.Account          `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}
