// Code generated by scalr-gen. DO NOT EDIT.

package plan

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to Plan operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new Plan client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Download JSON formatted execution plan.
func (c *Client) GetJsonOutputRaw(ctx context.Context, plan string, opts *GetJsonOutputOptions) (*client.Response, error) {
	path := "/plans/{plan}/json-output"
	path = strings.ReplaceAll(path, "{plan}", url.PathEscape(plan))

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Format (string)
		if opts.Format != "" {
			params.Set("format", opts.Format)
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Download JSON formatted execution plan.
func (c *Client) GetJsonOutput(ctx context.Context, plan string, opts *GetJsonOutputOptions) (string, error) {
	resp, err := c.GetJsonOutputRaw(ctx, plan, opts)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}

// GetJsonOutputOptions holds optional parameters for GetJsonOutput
type GetJsonOutputOptions struct {
	// Format of the response.
	Format string
	Filter map[string]string
}

// Show details of a specific Terraform Plan stage.
func (c *Client) GetPlanRaw(ctx context.Context, plan string) (*client.Response, error) {
	path := "/plans/{plan}"
	path = strings.ReplaceAll(path, "{plan}", url.PathEscape(plan))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Show details of a specific Terraform Plan stage.
func (c *Client) GetPlan(ctx context.Context, plan string) (*schemas.Plan, error) {
	resp, err := c.GetPlanRaw(ctx, plan)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.Plan             `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &result.Data, nil
}

// Download the raw output of the terraform plan stage.
func (c *Client) GetPlanLogRaw(ctx context.Context, plan string, opts *GetPlanLogOptions) (*client.Response, error) {
	path := "/plans/{plan}/output"
	path = strings.ReplaceAll(path, "{plan}", url.PathEscape(plan))

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Clean (bool)
		params.Set("clean", fmt.Sprintf("%t", opts.Clean))
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Download the raw output of the terraform plan stage.
func (c *Client) GetPlanLog(ctx context.Context, plan string, opts *GetPlanLogOptions) (string, error) {
	resp, err := c.GetPlanLogRaw(ctx, plan, opts)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}

// GetPlanLogOptions holds optional parameters for GetPlanLog
type GetPlanLogOptions struct {
	// Strip ANSI escape codes.
	Clean  bool
	Filter map[string]string
}

// Download plan file in machine-readable format with sanitized sensitive values.
func (c *Client) GetSanitizedJsonOutputRaw(ctx context.Context, plan string, opts *GetSanitizedJsonOutputOptions) (*client.Response, error) {
	path := "/plans/{plan}/sanitized-json-output"
	path = strings.ReplaceAll(path, "{plan}", url.PathEscape(plan))

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Format (string)
		if opts.Format != "" {
			params.Set("format", opts.Format)
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Download plan file in machine-readable format with sanitized sensitive values.
func (c *Client) GetSanitizedJsonOutput(ctx context.Context, plan string, opts *GetSanitizedJsonOutputOptions) (string, error) {
	resp, err := c.GetSanitizedJsonOutputRaw(ctx, plan, opts)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}

// GetSanitizedJsonOutputOptions holds optional parameters for GetSanitizedJsonOutput
type GetSanitizedJsonOutputOptions struct {
	// Format of the response.
	Format string
	Filter map[string]string
}
