// Code generated by scalr-gen. DO NOT EDIT.

package module_version

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to ModuleVersion operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new ModuleVersion client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Show details of a specific terraform module version.
func (c *Client) GetModuleVersionRaw(ctx context.Context, moduleVersion string, opts *GetModuleVersionOptions) (*client.Response, error) {
	path := "/module-versions/{module_version}"
	path = strings.ReplaceAll(path, "{module_version}", url.PathEscape(moduleVersion))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Show details of a specific terraform module version.
func (c *Client) GetModuleVersion(ctx context.Context, moduleVersion string, opts *GetModuleVersionOptions) (*schemas.ModuleVersion, error) {
	resp, err := c.GetModuleVersionRaw(ctx, moduleVersion, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.ModuleVersion    `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}

// GetModuleVersionOptions holds optional parameters for GetModuleVersion
type GetModuleVersionOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint lists versions of a particular module. The query parameter `filter[module]` with Module ID is required.
func (c *Client) ListModuleVersionsRaw(ctx context.Context, opts *ListModuleVersionsOptions) (*client.Response, error) {
	path := "/module-versions"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint lists versions of a particular module. The query parameter `filter[module]` with Module ID is required.
func (c *Client) ListModuleVersions(ctx context.Context, opts *ListModuleVersionsOptions) ([]*schemas.ModuleVersion, error) {
	resp, err := c.ListModuleVersionsRaw(ctx, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data []schemas.ModuleVersion `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.ModuleVersion, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	return resources, nil
}

// ListModuleVersionsIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.ModuleVersion.ListModuleVersionsIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListModuleVersionsIter(ctx context.Context, opts *ListModuleVersionsOptions) iter.Seq2[schemas.ModuleVersion, error] {
	return func(yield func(schemas.ModuleVersion, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.ModuleVersion{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListModuleVersionsOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page using Raw method to get pagination metadata
			resp, err := c.ListModuleVersionsRaw(ctx, pageOpts)
			if err != nil {
				yield(schemas.ModuleVersion{}, err)
				return
			}
			defer resp.Body.Close()

			// Decode response
			var result struct {
				Data []schemas.ModuleVersion `json:"data"`
				Meta struct {
					Pagination *client.Pagination `json:"pagination"`
				} `json:"meta"`
				Included []map[string]interface{} `json:"included"`
			}
			if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
				yield(schemas.ModuleVersion{}, fmt.Errorf("failed to decode response: %w", err))
				return
			}

			// Yield each item
			for i := range result.Data {
				// Populate included resources into relationships
				if len(result.Included) > 0 {
					result.Data[i].Relationships.PopulateIncludes(result.Included)
				}
				if !yield(result.Data[i], nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if result.Meta.Pagination == nil || result.Meta.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListModuleVersionsPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.ModuleVersion.ListModuleVersionsPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListModuleVersionsPaged(ctx context.Context, opts *ListModuleVersionsOptions) *client.Iterator[schemas.ModuleVersion] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.ModuleVersion, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListModuleVersionsOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the Raw method to get pagination metadata
		resp, err := c.ListModuleVersionsRaw(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}
		defer resp.Body.Close()

		// Decode response
		var result struct {
			Data []schemas.ModuleVersion `json:"data"`
			Meta struct {
				Pagination *client.Pagination `json:"pagination"`
			} `json:"meta"`
			Included []map[string]interface{} `json:"included"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			return nil, nil, fmt.Errorf("failed to decode response: %w", err)
		}

		// Convert to slice of pointers and populate includes
		items := make([]*schemas.ModuleVersion, len(result.Data))
		for i := range result.Data {
			items[i] = &result.Data[i]
			// Populate included resources into relationships
			if len(result.Included) > 0 {
				items[i].Relationships.PopulateIncludes(result.Included)
			}
		}

		return items, result.Meta.Pagination, nil
	}

	return client.NewIterator[schemas.ModuleVersion](ctx, pageSize, fetchPage)
}

// ListModuleVersionsOptions holds optional parameters for ListModuleVersions
type ListModuleVersionsOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort []string
	// The comma-separated list of relationship paths.
	Include []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}

// Trigger resync of the Module Version associated with the `relationships.vcs-revision`. Only modules associated with a VCS can be resynchronized.
func (c *Client) ResyncModuleVersionRaw(ctx context.Context, moduleVersion string) (*client.Response, error) {
	path := "/module-versions/{module_version}/actions/resync"
	path = strings.ReplaceAll(path, "{module_version}", url.PathEscape(moduleVersion))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Trigger resync of the Module Version associated with the `relationships.vcs-revision`. Only modules associated with a VCS can be resynchronized.
func (c *Client) ResyncModuleVersion(ctx context.Context, moduleVersion string) error {
	resp, err := c.ResyncModuleVersionRaw(ctx, moduleVersion)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}
