// Code generated by scalr-gen. DO NOT EDIT.

package wiz_integration

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to WizIntegration operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new WizIntegration client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint creates a Wiz integration.
func (c *Client) CreateWizIntegrationRaw(ctx context.Context, req *schemas.WizIntegrationRequest, opts *CreateWizIntegrationOptions) (*client.Response, error) {
	path := "/integrations/wiz"

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	httpResp, err := c.httpClient.Post(ctx, path, body, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint creates a Wiz integration.
func (c *Client) CreateWizIntegration(ctx context.Context, req *schemas.WizIntegrationRequest, opts *CreateWizIntegrationOptions) (*schemas.WizIntegration, error) {
	resp, err := c.CreateWizIntegrationRaw(ctx, req, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.WizIntegration   `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}

// CreateWizIntegrationOptions holds optional parameters for CreateWizIntegration
type CreateWizIntegrationOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

func (c *Client) DeleteWizIntegrationRaw(ctx context.Context, wizIntegration string) (*client.Response, error) {
	path := "/integrations/wiz/{wiz_integration}"
	path = strings.ReplaceAll(path, "{wiz_integration}", url.PathEscape(wizIntegration))

	httpResp, err := c.httpClient.Delete(ctx, path, nil, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

func (c *Client) DeleteWizIntegration(ctx context.Context, wizIntegration string) error {
	resp, err := c.DeleteWizIntegrationRaw(ctx, wizIntegration)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// Show details of a specific Wiz integration.
func (c *Client) GetWizIntegrationRaw(ctx context.Context, wizIntegration string, opts *GetWizIntegrationOptions) (*client.Response, error) {
	path := "/integrations/wiz/{wiz_integration}"
	path = strings.ReplaceAll(path, "{wiz_integration}", url.PathEscape(wizIntegration))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Show details of a specific Wiz integration.
func (c *Client) GetWizIntegration(ctx context.Context, wizIntegration string, opts *GetWizIntegrationOptions) (*schemas.WizIntegration, error) {
	resp, err := c.GetWizIntegrationRaw(ctx, wizIntegration, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.WizIntegration   `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}

// GetWizIntegrationOptions holds optional parameters for GetWizIntegration
type GetWizIntegrationOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint returns a list of Wiz integrations.
func (c *Client) ListWizIntegrationsRaw(ctx context.Context, opts *ListWizIntegrationsOptions) (*client.Response, error) {
	path := "/integrations/wiz"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint returns a list of Wiz integrations.
func (c *Client) ListWizIntegrations(ctx context.Context, opts *ListWizIntegrationsOptions) ([]*schemas.WizIntegration, error) {
	resp, err := c.ListWizIntegrationsRaw(ctx, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data []schemas.WizIntegration `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.WizIntegration, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	return resources, nil
}

// ListWizIntegrationsIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.WizIntegration.ListWizIntegrationsIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListWizIntegrationsIter(ctx context.Context, opts *ListWizIntegrationsOptions) iter.Seq2[schemas.WizIntegration, error] {
	return func(yield func(schemas.WizIntegration, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.WizIntegration{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListWizIntegrationsOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page using Raw method to get pagination metadata
			resp, err := c.ListWizIntegrationsRaw(ctx, pageOpts)
			if err != nil {
				yield(schemas.WizIntegration{}, err)
				return
			}
			defer resp.Body.Close()

			// Decode response
			var result struct {
				Data []schemas.WizIntegration `json:"data"`
				Meta struct {
					Pagination *client.Pagination `json:"pagination"`
				} `json:"meta"`
				Included []map[string]interface{} `json:"included"`
			}
			if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
				yield(schemas.WizIntegration{}, fmt.Errorf("failed to decode response: %w", err))
				return
			}

			// Yield each item
			for i := range result.Data {
				// Populate included resources into relationships
				if len(result.Included) > 0 {
					result.Data[i].Relationships.PopulateIncludes(result.Included)
				}
				if !yield(result.Data[i], nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if result.Meta.Pagination == nil || result.Meta.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListWizIntegrationsPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.WizIntegration.ListWizIntegrationsPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListWizIntegrationsPaged(ctx context.Context, opts *ListWizIntegrationsOptions) *client.Iterator[schemas.WizIntegration] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.WizIntegration, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListWizIntegrationsOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the Raw method to get pagination metadata
		resp, err := c.ListWizIntegrationsRaw(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}
		defer resp.Body.Close()

		// Decode response
		var result struct {
			Data []schemas.WizIntegration `json:"data"`
			Meta struct {
				Pagination *client.Pagination `json:"pagination"`
			} `json:"meta"`
			Included []map[string]interface{} `json:"included"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			return nil, nil, fmt.Errorf("failed to decode response: %w", err)
		}

		// Convert to slice of pointers and populate includes
		items := make([]*schemas.WizIntegration, len(result.Data))
		for i := range result.Data {
			items[i] = &result.Data[i]
			// Populate included resources into relationships
			if len(result.Included) > 0 {
				items[i].Relationships.PopulateIncludes(result.Included)
			}
		}

		return items, result.Meta.Pagination, nil
	}

	return client.NewIterator[schemas.WizIntegration](ctx, pageSize, fetchPage)
}

// ListWizIntegrationsOptions holds optional parameters for ListWizIntegrations
type ListWizIntegrationsOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of relationship paths.
	Include []string
	// The comma-separated list of attributes.
	Sort   []string
	Filter map[string]string
}

// This endpoint updates a Wiz integration.
func (c *Client) UpdateWizIntegrationRaw(ctx context.Context, wizIntegration string, req *schemas.WizIntegrationRequest, opts *UpdateWizIntegrationOptions) (*client.Response, error) {
	path := "/integrations/wiz/{wiz_integration}"
	path = strings.ReplaceAll(path, "{wiz_integration}", url.PathEscape(wizIntegration))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	httpResp, err := c.httpClient.Patch(ctx, path, body, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint updates a Wiz integration.
func (c *Client) UpdateWizIntegration(ctx context.Context, wizIntegration string, req *schemas.WizIntegrationRequest, opts *UpdateWizIntegrationOptions) (*schemas.WizIntegration, error) {
	resp, err := c.UpdateWizIntegrationRaw(ctx, wizIntegration, req, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.WizIntegration   `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}

// UpdateWizIntegrationOptions holds optional parameters for UpdateWizIntegration
type UpdateWizIntegrationOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}
