// Code generated by scalr-gen. DO NOT EDIT.

package saml_integration

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to SamlIntegration operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new SamlIntegration client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Create SAML Integration.
func (c *Client) CreateSamlIntegrationRaw(ctx context.Context, req *schemas.SamlIntegrationRequest) (*http.Response, error) {
	path := "/integrations/saml"

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// Create SAML Integration.
func (c *Client) CreateSamlIntegration(ctx context.Context, req *schemas.SamlIntegrationRequest) (*schemas.SamlIntegration, *client.Response, error) {
	httpResp, err := c.CreateSamlIntegrationRaw(ctx, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.SamlIntegration  `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// Delete SAML Integration.
func (c *Client) DeleteSamlIntegrationRaw(ctx context.Context, samlIntegration string) (*http.Response, error) {
	path := "/integrations/saml/{saml_integration}"
	path = strings.ReplaceAll(path, "{saml_integration}", url.PathEscape(samlIntegration))

	return c.httpClient.Delete(ctx, path, nil)
}

// Delete SAML Integration.
func (c *Client) DeleteSamlIntegration(ctx context.Context, samlIntegration string) (*client.Response, error) {
	httpResp, err := c.DeleteSamlIntegrationRaw(ctx, samlIntegration)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Show details of a specific SAML Integration.
func (c *Client) GetSamlIntegrationRaw(ctx context.Context, samlIntegration string) (*http.Response, error) {
	path := "/integrations/saml/{saml_integration}"
	path = strings.ReplaceAll(path, "{saml_integration}", url.PathEscape(samlIntegration))

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific SAML Integration.
func (c *Client) GetSamlIntegration(ctx context.Context, samlIntegration string) (*schemas.SamlIntegration, *client.Response, error) {
	httpResp, err := c.GetSamlIntegrationRaw(ctx, samlIntegration)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.SamlIntegration  `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// This endpoint lists SAML integrations.
func (c *Client) ListSamlIntegrationsRaw(ctx context.Context, opts *ListSamlIntegrationsOptions) (*http.Response, error) {
	path := "/integrations/saml"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists SAML integrations.
func (c *Client) ListSamlIntegrations(ctx context.Context, opts *ListSamlIntegrationsOptions) ([]*schemas.SamlIntegration, *client.Response, error) {
	httpResp, err := c.ListSamlIntegrationsRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.SamlIntegration `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.SamlIntegration, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListSamlIntegrationsIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.SamlIntegration.ListSamlIntegrationsIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListSamlIntegrationsIter(ctx context.Context, opts *ListSamlIntegrationsOptions) iter.Seq2[schemas.SamlIntegration, error] {
	return func(yield func(schemas.SamlIntegration, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.SamlIntegration{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListSamlIntegrationsOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListSamlIntegrations(ctx, pageOpts)
			if err != nil {
				yield(schemas.SamlIntegration{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListSamlIntegrationsPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.SamlIntegration.ListSamlIntegrationsPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListSamlIntegrationsPaged(ctx context.Context, opts *ListSamlIntegrationsOptions) *client.Iterator[schemas.SamlIntegration] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.SamlIntegration, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListSamlIntegrationsOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListSamlIntegrations(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.SamlIntegration](ctx, pageSize, fetchPage)
}

// ListSamlIntegrationsOptions holds optional parameters for ListSamlIntegrations
type ListSamlIntegrationsOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort   []string
	Filter map[string]string
}

// Update SAML Integration.
func (c *Client) UpdateSamlIntegrationRaw(ctx context.Context, samlIntegration string, req *schemas.SamlIntegrationRequest) (*http.Response, error) {
	path := "/integrations/saml/{saml_integration}"
	path = strings.ReplaceAll(path, "{saml_integration}", url.PathEscape(samlIntegration))

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Patch(ctx, path, body, nil)
}

// Update SAML Integration.
func (c *Client) UpdateSamlIntegration(ctx context.Context, samlIntegration string, req *schemas.SamlIntegrationRequest) (*schemas.SamlIntegration, *client.Response, error) {
	httpResp, err := c.UpdateSamlIntegrationRaw(ctx, samlIntegration, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.SamlIntegration  `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}
