// Code generated by scalr-gen. DO NOT EDIT.

package misc

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to Misc operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new Misc client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

func (c *Client) CreateVcsTaskRaw(ctx context.Context, req *schemas.VcsTaskRequest) (*client.Response, error) {
	path := "/vcs-tasks"

	// Plain JSON request (not JSON:API)
	headers := map[string]string{"Content-Type": "application/json"}
	httpResp, err := c.httpClient.Post(ctx, path, req, headers)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

func (c *Client) CreateVcsTask(ctx context.Context, req *schemas.VcsTaskRequest) error {
	resp, err := c.CreateVcsTaskRaw(ctx, req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// Creates a link between a workspace and an SSH key.
func (c *Client) CreateWorkspaceSshKeyLinkRaw(ctx context.Context, workspace string, req *schemas.WorkspaceSSHKeyLinkRequest) (*client.Response, error) {
	path := "/workspaces/{workspace}/ssh-key-links"
	path = strings.ReplaceAll(path, "{workspace}", url.PathEscape(workspace))

	// Plain JSON request (not JSON:API)
	headers := map[string]string{"Content-Type": "application/json"}
	httpResp, err := c.httpClient.Post(ctx, path, req, headers)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Creates a link between a workspace and an SSH key.
func (c *Client) CreateWorkspaceSshKeyLink(ctx context.Context, workspace string, req *schemas.WorkspaceSSHKeyLinkRequest) (*schemas.Workspace, error) {
	resp, err := c.CreateWorkspaceSshKeyLinkRaw(ctx, workspace, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.Workspace        `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}

// Deletes a link between a workspace and an SSH key.
func (c *Client) DeleteWorkspaceSshKeyLinkRaw(ctx context.Context, workspace string) (*client.Response, error) {
	path := "/workspaces/{workspace}/ssh-key-links"
	path = strings.ReplaceAll(path, "{workspace}", url.PathEscape(workspace))

	httpResp, err := c.httpClient.Delete(ctx, path, nil, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Deletes a link between a workspace and an SSH key.
func (c *Client) DeleteWorkspaceSshKeyLink(ctx context.Context, workspace string) error {
	resp, err := c.DeleteWorkspaceSshKeyLinkRaw(ctx, workspace)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

func (c *Client) GetOpenMetricsRaw(ctx context.Context) (*client.Response, error) {
	path := "/metrics"

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

func (c *Client) GetOpenMetrics(ctx context.Context) (string, error) {
	resp, err := c.GetOpenMetricsRaw(ctx)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}

// Destroys user's session. In case of the SAML additionally performs SAML logout action.
func (c *Client) LogoutRaw(ctx context.Context) (*client.Response, error) {
	path := "/logout"

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Destroys user's session. In case of the SAML additionally performs SAML logout action.
func (c *Client) Logout(ctx context.Context) error {
	resp, err := c.LogoutRaw(ctx)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

func (c *Client) OauthSigninRaw(ctx context.Context, provider string) (*client.Response, error) {
	path := "/iam/signin/{provider}"
	path = strings.ReplaceAll(path, "{provider}", url.PathEscape(provider))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

func (c *Client) OauthSignin(ctx context.Context, provider string) error {
	resp, err := c.OauthSigninRaw(ctx, provider)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

func (c *Client) OauthSignupRaw(ctx context.Context, provider string) (*client.Response, error) {
	path := "/iam/signup/{provider}"
	path = strings.ReplaceAll(path, "{provider}", url.PathEscape(provider))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

func (c *Client) OauthSignup(ctx context.Context, provider string) error {
	resp, err := c.OauthSignupRaw(ctx, provider)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// Checks the connection to the API server
func (c *Client) PingRaw(ctx context.Context) (*client.Response, error) {
	path := "/ping"

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Checks the connection to the API server
func (c *Client) Ping(ctx context.Context) (string, error) {
	resp, err := c.PingRaw(ctx)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}
