// Code generated by scalr-gen. DO NOT EDIT.

package access_policy

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to AccessPolicy operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new AccessPolicy client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Grant access for a member identity to a scope identity. Access is a set of `roles`. Member identity might be one of `user`, `team`, or `service-account`. Scope identity is one of `account`, `environment`, or `workspace`. Check out [identity and access management](https://docs.scalr.io/docs/identity-and-access-management) for a detailed description of the Scalr IAM model.
func (c *Client) CreateAccessPolicyRaw(ctx context.Context, req *schemas.AccessPolicyRequest, opts *CreateAccessPolicyOptions) (*http.Response, error) {
	path := "/access-policies"

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// Grant access for a member identity to a scope identity. Access is a set of `roles`. Member identity might be one of `user`, `team`, or `service-account`. Scope identity is one of `account`, `environment`, or `workspace`. Check out [identity and access management](https://docs.scalr.io/docs/identity-and-access-management) for a detailed description of the Scalr IAM model.
func (c *Client) CreateAccessPolicy(ctx context.Context, req *schemas.AccessPolicyRequest, opts *CreateAccessPolicyOptions) (*schemas.AccessPolicy, *client.Response, error) {
	httpResp, err := c.CreateAccessPolicyRaw(ctx, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessPolicy     `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// CreateAccessPolicyOptions holds optional parameters for CreateAccessPolicy
type CreateAccessPolicyOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

func (c *Client) DeleteAccessPolicyRaw(ctx context.Context, accessPolicy string) (*http.Response, error) {
	path := "/access-policies/{access_policy}"
	path = strings.ReplaceAll(path, "{access_policy}", url.PathEscape(accessPolicy))

	return c.httpClient.Delete(ctx, path, nil, nil)
}

func (c *Client) DeleteAccessPolicy(ctx context.Context, accessPolicy string) (*client.Response, error) {
	httpResp, err := c.DeleteAccessPolicyRaw(ctx, accessPolicy)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// This endpoint returns a list of [IAM](https://docs.scalr.io/docs/identity-and-access-management) access policies.
func (c *Client) GetAccessPoliciesRaw(ctx context.Context, opts *GetAccessPoliciesOptions) (*http.Response, error) {
	path := "/access-policies"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint returns a list of [IAM](https://docs.scalr.io/docs/identity-and-access-management) access policies.
func (c *Client) GetAccessPolicies(ctx context.Context, opts *GetAccessPoliciesOptions) ([]*schemas.AccessPolicy, *client.Response, error) {
	httpResp, err := c.GetAccessPoliciesRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.AccessPolicy `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.AccessPolicy, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// GetAccessPoliciesIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.AccessPolicy.GetAccessPoliciesIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) GetAccessPoliciesIter(ctx context.Context, opts *GetAccessPoliciesOptions) iter.Seq2[schemas.AccessPolicy, error] {
	return func(yield func(schemas.AccessPolicy, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.AccessPolicy{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &GetAccessPoliciesOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.GetAccessPolicies(ctx, pageOpts)
			if err != nil {
				yield(schemas.AccessPolicy{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// GetAccessPoliciesPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.AccessPolicy.GetAccessPoliciesPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) GetAccessPoliciesPaged(ctx context.Context, opts *GetAccessPoliciesOptions) *client.Iterator[schemas.AccessPolicy] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.AccessPolicy, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &GetAccessPoliciesOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.GetAccessPolicies(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.AccessPolicy](ctx, pageSize, fetchPage)
}

// GetAccessPoliciesOptions holds optional parameters for GetAccessPolicies
type GetAccessPoliciesOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// Query string
	Query string
	// The comma-separated list of attributes.
	Sort []string
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// The endpoint returns [IAM](https://docs.scalr.io/docs/identity-and-access-management) access policy by ID.
func (c *Client) GetAccessPolicyRaw(ctx context.Context, accessPolicy string, opts *GetAccessPolicyOptions) (*http.Response, error) {
	path := "/access-policies/{access_policy}"
	path = strings.ReplaceAll(path, "{access_policy}", url.PathEscape(accessPolicy))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// The endpoint returns [IAM](https://docs.scalr.io/docs/identity-and-access-management) access policy by ID.
func (c *Client) GetAccessPolicy(ctx context.Context, accessPolicy string, opts *GetAccessPolicyOptions) (*schemas.AccessPolicy, *client.Response, error) {
	httpResp, err := c.GetAccessPolicyRaw(ctx, accessPolicy, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessPolicy     `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetAccessPolicyOptions holds optional parameters for GetAccessPolicy
type GetAccessPolicyOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

func (c *Client) UpdateAccessPolicyRaw(ctx context.Context, accessPolicy string, req *schemas.AccessPolicyRequest, opts *UpdateAccessPolicyOptions) (*http.Response, error) {
	path := "/access-policies/{access_policy}"
	path = strings.ReplaceAll(path, "{access_policy}", url.PathEscape(accessPolicy))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Patch(ctx, path, body, nil)
}

func (c *Client) UpdateAccessPolicy(ctx context.Context, accessPolicy string, req *schemas.AccessPolicyRequest, opts *UpdateAccessPolicyOptions) (*schemas.AccessPolicy, *client.Response, error) {
	httpResp, err := c.UpdateAccessPolicyRaw(ctx, accessPolicy, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessPolicy     `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// UpdateAccessPolicyOptions holds optional parameters for UpdateAccessPolicy
type UpdateAccessPolicyOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}
