// Code generated by scalr-gen. DO NOT EDIT.

package access_token

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to AccessToken operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new AccessToken client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint creates service account's access token.
func (c *Client) AssumeServiceAccountRaw(ctx context.Context, req *schemas.AssumeServiceAccountRequest) (*http.Response, error) {
	path := "/service-accounts/assume"

	// Plain JSON request (not JSON:API)
	headers := map[string]string{"Content-Type": "application/json"}
	return c.httpClient.Post(ctx, path, req, headers)
}

// This endpoint creates service account's access token.
func (c *Client) AssumeServiceAccount(ctx context.Context, req *schemas.AssumeServiceAccountRequest) (string, *client.Response, error) {
	httpResp, err := c.AssumeServiceAccountRaw(ctx, req)
	if err != nil {
		return "", nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	bodyBytes, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return "", resp, fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), resp, nil
}

// This endpoint creates access token.
func (c *Client) CreateAccessTokenRaw(ctx context.Context, req *schemas.AccessTokenRequest, opts *CreateAccessTokenOptions) (*http.Response, error) {
	path := "/access-tokens"

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// This endpoint creates access token.
func (c *Client) CreateAccessToken(ctx context.Context, req *schemas.AccessTokenRequest, opts *CreateAccessTokenOptions) (*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.CreateAccessTokenRaw(ctx, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessToken      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// CreateAccessTokenOptions holds optional parameters for CreateAccessToken
type CreateAccessTokenOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint creates agent pool's access token.
func (c *Client) CreateAgentPoolTokenRaw(ctx context.Context, agentPool string, req *schemas.AccessTokenRequest, opts *CreateAgentPoolTokenOptions) (*http.Response, error) {
	path := "/agent-pools/{agent_pool}/access-tokens"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// This endpoint creates agent pool's access token.
func (c *Client) CreateAgentPoolToken(ctx context.Context, agentPool string, req *schemas.AccessTokenRequest, opts *CreateAgentPoolTokenOptions) (*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.CreateAgentPoolTokenRaw(ctx, agentPool, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessToken      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// CreateAgentPoolTokenOptions holds optional parameters for CreateAgentPoolToken
type CreateAgentPoolTokenOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint creates service account's access token.
func (c *Client) CreateServiceAccountTokenRaw(ctx context.Context, serviceAccount string, req *schemas.AccessTokenRequest, opts *CreateServiceAccountTokenOptions) (*http.Response, error) {
	path := "/service-accounts/{service_account}/access-tokens"
	path = strings.ReplaceAll(path, "{service_account}", url.PathEscape(serviceAccount))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// This endpoint creates service account's access token.
func (c *Client) CreateServiceAccountToken(ctx context.Context, serviceAccount string, req *schemas.AccessTokenRequest, opts *CreateServiceAccountTokenOptions) (*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.CreateServiceAccountTokenRaw(ctx, serviceAccount, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessToken      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// CreateServiceAccountTokenOptions holds optional parameters for CreateServiceAccountToken
type CreateServiceAccountTokenOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// Delete an access token by ID.
func (c *Client) DeleteAccessTokenRaw(ctx context.Context, accessToken string) (*http.Response, error) {
	path := "/access-tokens/{access_token}"
	path = strings.ReplaceAll(path, "{access_token}", url.PathEscape(accessToken))

	return c.httpClient.Delete(ctx, path, nil, nil)
}

// Delete an access token by ID.
func (c *Client) DeleteAccessToken(ctx context.Context, accessToken string) (*client.Response, error) {
	httpResp, err := c.DeleteAccessTokenRaw(ctx, accessToken)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Get an access token by ID.
func (c *Client) GetAccessTokenRaw(ctx context.Context, accessToken string, opts *GetAccessTokenOptions) (*http.Response, error) {
	path := "/access-tokens/{access_token}"
	path = strings.ReplaceAll(path, "{access_token}", url.PathEscape(accessToken))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Get an access token by ID.
func (c *Client) GetAccessToken(ctx context.Context, accessToken string, opts *GetAccessTokenOptions) (*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.GetAccessTokenRaw(ctx, accessToken, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessToken      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetAccessTokenOptions holds optional parameters for GetAccessToken
type GetAccessTokenOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint lists user access tokens.
func (c *Client) ListAccessTokensRaw(ctx context.Context, opts *ListAccessTokensOptions) (*http.Response, error) {
	path := "/access-tokens"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists user access tokens.
func (c *Client) ListAccessTokens(ctx context.Context, opts *ListAccessTokensOptions) ([]*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.ListAccessTokensRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.AccessToken `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.AccessToken, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListAccessTokensIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.AccessToken.ListAccessTokensIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListAccessTokensIter(ctx context.Context, opts *ListAccessTokensOptions) iter.Seq2[schemas.AccessToken, error] {
	return func(yield func(schemas.AccessToken, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.AccessToken{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListAccessTokensOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListAccessTokens(ctx, pageOpts)
			if err != nil {
				yield(schemas.AccessToken{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListAccessTokensPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.AccessToken.ListAccessTokensPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListAccessTokensPaged(ctx context.Context, opts *ListAccessTokensOptions) *client.Iterator[schemas.AccessToken] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.AccessToken, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListAccessTokensOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListAccessTokens(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.AccessToken](ctx, pageSize, fetchPage)
}

// ListAccessTokensOptions holds optional parameters for ListAccessTokens
type ListAccessTokensOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort []string
	// The comma-separated list of relationship paths.
	Include []string
	// Query string
	Query  string
	Filter map[string]string
}

func (c *Client) ListAgentPoolAccessTokensRaw(ctx context.Context, agentPool string, opts *ListAgentPoolAccessTokensOptions) (*http.Response, error) {
	path := "/agent-pools/{agent_pool}/access-tokens"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

func (c *Client) ListAgentPoolAccessTokens(ctx context.Context, agentPool string, opts *ListAgentPoolAccessTokensOptions) ([]*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.ListAgentPoolAccessTokensRaw(ctx, agentPool, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.AccessToken `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.AccessToken, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListAgentPoolAccessTokensIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.AccessToken.ListAgentPoolAccessTokensIter(ctx, agentPool, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListAgentPoolAccessTokensIter(ctx context.Context, agentPool string, opts *ListAgentPoolAccessTokensOptions) iter.Seq2[schemas.AccessToken, error] {
	return func(yield func(schemas.AccessToken, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.AccessToken{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListAgentPoolAccessTokensOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListAgentPoolAccessTokens(ctx, agentPool, pageOpts)
			if err != nil {
				yield(schemas.AccessToken{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListAgentPoolAccessTokensPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.AccessToken.ListAgentPoolAccessTokensPaged(ctx, agentPool, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListAgentPoolAccessTokensPaged(ctx context.Context, agentPool string, opts *ListAgentPoolAccessTokensOptions) *client.Iterator[schemas.AccessToken] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.AccessToken, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListAgentPoolAccessTokensOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListAgentPoolAccessTokens(ctx, agentPool, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.AccessToken](ctx, pageSize, fetchPage)
}

// ListAgentPoolAccessTokensOptions holds optional parameters for ListAgentPoolAccessTokens
type ListAgentPoolAccessTokensOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort []string
	// The comma-separated list of relationship paths.
	Include []string
	// Query string
	Query  string
	Filter map[string]string
}

// This endpoint lists service account's access tokens.
func (c *Client) ListServiceAccountAccessTokensRaw(ctx context.Context, serviceAccount string, opts *ListServiceAccountAccessTokensOptions) (*http.Response, error) {
	path := "/service-accounts/{service_account}/access-tokens"
	path = strings.ReplaceAll(path, "{service_account}", url.PathEscape(serviceAccount))

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists service account's access tokens.
func (c *Client) ListServiceAccountAccessTokens(ctx context.Context, serviceAccount string, opts *ListServiceAccountAccessTokensOptions) ([]*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.ListServiceAccountAccessTokensRaw(ctx, serviceAccount, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.AccessToken `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.AccessToken, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListServiceAccountAccessTokensIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.AccessToken.ListServiceAccountAccessTokensIter(ctx, serviceAccount, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListServiceAccountAccessTokensIter(ctx context.Context, serviceAccount string, opts *ListServiceAccountAccessTokensOptions) iter.Seq2[schemas.AccessToken, error] {
	return func(yield func(schemas.AccessToken, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.AccessToken{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListServiceAccountAccessTokensOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListServiceAccountAccessTokens(ctx, serviceAccount, pageOpts)
			if err != nil {
				yield(schemas.AccessToken{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListServiceAccountAccessTokensPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.AccessToken.ListServiceAccountAccessTokensPaged(ctx, serviceAccount, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListServiceAccountAccessTokensPaged(ctx context.Context, serviceAccount string, opts *ListServiceAccountAccessTokensOptions) *client.Iterator[schemas.AccessToken] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.AccessToken, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListServiceAccountAccessTokensOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListServiceAccountAccessTokens(ctx, serviceAccount, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.AccessToken](ctx, pageSize, fetchPage)
}

// ListServiceAccountAccessTokensOptions holds optional parameters for ListServiceAccountAccessTokens
type ListServiceAccountAccessTokensOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort []string
	// The comma-separated list of relationship paths.
	Include []string
	// Query string
	Query  string
	Filter map[string]string
}

// Update an access token by ID.
func (c *Client) UpdateAccessTokenRaw(ctx context.Context, accessToken string, req *schemas.AccessTokenRequest, opts *UpdateAccessTokenOptions) (*http.Response, error) {
	path := "/access-tokens/{access_token}"
	path = strings.ReplaceAll(path, "{access_token}", url.PathEscape(accessToken))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Patch(ctx, path, body, nil)
}

// Update an access token by ID.
func (c *Client) UpdateAccessToken(ctx context.Context, accessToken string, req *schemas.AccessTokenRequest, opts *UpdateAccessTokenOptions) (*schemas.AccessToken, *client.Response, error) {
	httpResp, err := c.UpdateAccessTokenRaw(ctx, accessToken, req, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.AccessToken      `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// UpdateAccessTokenOptions holds optional parameters for UpdateAccessToken
type UpdateAccessTokenOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}
