// Code generated by scalr-gen. DO NOT EDIT.

package terraform_version_usage

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to TerraformVersionUsage operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new TerraformVersionUsage client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint lists terraform versions usage.
func (c *Client) ListTerraformVersionsUsageRaw(ctx context.Context, opts *ListTerraformVersionsUsageOptions) (*client.Response, error) {
	path := "/reports/tf-versions-usage"

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		// Handle parameter: Format (string)
		if opts.Format != "" {
			params.Set("format", opts.Format)
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint lists terraform versions usage.
func (c *Client) ListTerraformVersionsUsage(ctx context.Context, opts *ListTerraformVersionsUsageOptions) ([]*schemas.TerraformVersionUsage, error) {
	resp, err := c.ListTerraformVersionsUsageRaw(ctx, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data []schemas.TerraformVersionUsage `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.TerraformVersionUsage, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	return resources, nil
}

// ListTerraformVersionsUsageIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.TerraformVersionUsage.ListTerraformVersionsUsageIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListTerraformVersionsUsageIter(ctx context.Context, opts *ListTerraformVersionsUsageOptions) iter.Seq2[schemas.TerraformVersionUsage, error] {
	return func(yield func(schemas.TerraformVersionUsage, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.TerraformVersionUsage{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListTerraformVersionsUsageOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page using Raw method to get pagination metadata
			resp, err := c.ListTerraformVersionsUsageRaw(ctx, pageOpts)
			if err != nil {
				yield(schemas.TerraformVersionUsage{}, err)
				return
			}
			defer resp.Body.Close()

			// Decode response
			var result struct {
				Data []schemas.TerraformVersionUsage `json:"data"`
				Meta struct {
					Pagination *client.Pagination `json:"pagination"`
				} `json:"meta"`
				Included []map[string]interface{} `json:"included"`
			}
			if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
				yield(schemas.TerraformVersionUsage{}, fmt.Errorf("failed to decode response: %w", err))
				return
			}

			// Yield each item
			for i := range result.Data {
				// Populate included resources into relationships
				if len(result.Included) > 0 {
					result.Data[i].Relationships.PopulateIncludes(result.Included)
				}
				if !yield(result.Data[i], nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if result.Meta.Pagination == nil || result.Meta.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListTerraformVersionsUsagePaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.TerraformVersionUsage.ListTerraformVersionsUsagePaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListTerraformVersionsUsagePaged(ctx context.Context, opts *ListTerraformVersionsUsageOptions) *client.Iterator[schemas.TerraformVersionUsage] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.TerraformVersionUsage, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListTerraformVersionsUsageOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the Raw method to get pagination metadata
		resp, err := c.ListTerraformVersionsUsageRaw(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}
		defer resp.Body.Close()

		// Decode response
		var result struct {
			Data []schemas.TerraformVersionUsage `json:"data"`
			Meta struct {
				Pagination *client.Pagination `json:"pagination"`
			} `json:"meta"`
			Included []map[string]interface{} `json:"included"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			return nil, nil, fmt.Errorf("failed to decode response: %w", err)
		}

		// Convert to slice of pointers and populate includes
		items := make([]*schemas.TerraformVersionUsage, len(result.Data))
		for i := range result.Data {
			items[i] = &result.Data[i]
			// Populate included resources into relationships
			if len(result.Included) > 0 {
				items[i].Relationships.PopulateIncludes(result.Included)
			}
		}

		return items, result.Meta.Pagination, nil
	}

	return client.NewIterator[schemas.TerraformVersionUsage](ctx, pageSize, fetchPage)
}

// ListTerraformVersionsUsageOptions holds optional parameters for ListTerraformVersionsUsage
type ListTerraformVersionsUsageOptions struct {
	// The search string. Supports search by workspace name of terraform version usage.
	Query string
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// Format of the response. It can be 'json' or 'csv'.
	Format string
	// The comma-separated list of attributes.
	Sort []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint lists unique terraform versions in use.
func (c *Client) ListTerraformVersionsUsageVersionsRaw(ctx context.Context, opts *ListTerraformVersionsUsageVersionsOptions) (*client.Response, error) {
	path := "/reports/tf-versions-usage-versions"

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint lists unique terraform versions in use.
func (c *Client) ListTerraformVersionsUsageVersions(ctx context.Context, opts *ListTerraformVersionsUsageVersionsOptions) (string, error) {
	resp, err := c.ListTerraformVersionsUsageVersionsRaw(ctx, opts)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}

// ListTerraformVersionsUsageVersionsOptions holds optional parameters for ListTerraformVersionsUsageVersions
type ListTerraformVersionsUsageVersionsOptions struct {
	// Query string.
	Query string
	// Page number
	PageNumber int
	// Page size
	PageSize int
	Filter   map[string]string
}
