// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// AccountUserStatus represents the type for AccountUserStatus
// The relation status. Can be: `Active`, `Inactive`, `Pending`.
type AccountUserStatus string

// AccountUserStatus constants
const (
	AccountUserStatusActive   AccountUserStatus = "Active"
	AccountUserStatusInactive AccountUserStatus = "Inactive"
	AccountUserStatusPending  AccountUserStatus = "Pending"
)

// Response version - used when unmarshalling from API responses
// Represents an account-user relation.
type AccountUser struct {
	ID            string                   `json:"id"`
	Type          string                   `json:"type"`
	Attributes    AccountUserAttributes    `json:"attributes"`
	Relationships AccountUserRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r AccountUser) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r AccountUser) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "account-users"
}

// AccountUserAttributes holds the attributes for AccountUser (response)
type AccountUserAttributes struct {
	// The UTC timestamp when the user logged in to the account.
	LastLoginAt *time.Time `json:"last-login-at"`
	// The relation status. Can be: `Active`, `Inactive`, `Pending`.
	Status AccountUserStatus `json:"status"`
}

// AccountUserRelationships holds the relationships for AccountUser (response)
type AccountUserRelationships struct {
	Account *Account `json:"account"`
	Teams   []*Team  `json:"teams"`
	User    *User    `json:"user"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *AccountUserRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["account"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Account = &Account{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["teams"]; ok {
		// To-many relationship
		var rel struct {
			Data []struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Teams = make([]*Team, len(rel.Data))
			for i, d := range rel.Data {
				r.Teams[i] = &Team{
					ID:   d.ID,
					Type: d.Type,
				}
			}
		}
	}
	if raw, ok := temp["user"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.User = &User{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *AccountUserRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Account
	if r.Account != nil && r.Account.ID != "" {
		key := r.Account.Type + ":" + r.Account.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Account
			if err := json.Unmarshal(data, &full); err == nil {
				r.Account = &full
			}
		}
	}
	// Populate to-many relationship: Teams
	if r.Teams != nil {
		for i, resource := range r.Teams {
			if resource != nil && resource.ID != "" {
				key := resource.Type + ":" + resource.ID
				if fullResource, ok := includedMap[key]; ok {
					// Unmarshal the full resource
					data, _ := json.Marshal(fullResource)
					var full Team
					if err := json.Unmarshal(data, &full); err == nil {
						r.Teams[i] = &full
					}
				}
			}
		}
	}
	// Populate to-one relationship: User
	if r.User != nil && r.User.ID != "" {
		key := r.User.Type + ":" + r.User.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full User
			if err := json.Unmarshal(data, &full); err == nil {
				r.User = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// Represents an account-user relation. (for requests)
type AccountUserRequest struct {
	ID            string                          `json:"id,omitempty"`
	Type          string                          `json:"type,omitempty"`
	Attributes    AccountUserAttributesRequest    `json:"attributes,omitempty"`
	Relationships AccountUserRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r AccountUserRequest) MarshalJSON() ([]byte, error) {
	type Alias AccountUserRequest
	if r.Type == "" {
		r.Type = "account-users"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r AccountUserRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r AccountUserRequest) GetResourceType() string {
	return "account-users"
}

// AccountUserAttributesRequest holds the attributes for AccountUser (request)
type AccountUserAttributesRequest struct {
	// The UTC timestamp when the user logged in to the account.
	LastLoginAt *value.Value[time.Time] `json:"last-login-at,omitempty"`
	// The relation status. Can be: `Active`, `Inactive`, `Pending`.
	Status *value.Value[AccountUserStatus] `json:"status,omitempty"`
}

// AccountUserRelationshipsRequest holds the relationships for AccountUser (request)
type AccountUserRelationshipsRequest struct {
	Account *value.Value[Account] `json:"account,omitempty"`
	Teams   *value.Value[[]Team]  `json:"teams,omitempty"`
	User    *value.Value[User]    `json:"user,omitempty"`
}
