// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// AgentPoolMTLSCertificateStatus represents the type for AgentPoolMTLSCertificateStatus
// Certificate status: active, expired, or revoked.
type AgentPoolMTLSCertificateStatus string

// AgentPoolMTLSCertificateStatus constants
const (
	AgentPoolMTLSCertificateStatusActive  AgentPoolMTLSCertificateStatus = "active"
	AgentPoolMTLSCertificateStatusExpired AgentPoolMTLSCertificateStatus = "expired"
	AgentPoolMTLSCertificateStatusRevoked AgentPoolMTLSCertificateStatus = "revoked"
)

// Response version - used when unmarshalling from API responses
// An mTLS client certificate issued for an agent pool. Each certificate is bound to an agent pool and account. Its SHA-256 fingerprint is checked during mTLS enforcement to determine whether an agent connection is accepted.
type AgentPoolMTLSCertificate struct {
	ID            string                                `json:"id"`
	Type          string                                `json:"type"`
	Attributes    AgentPoolMTLSCertificateAttributes    `json:"attributes"`
	Relationships AgentPoolMTLSCertificateRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r AgentPoolMTLSCertificate) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r AgentPoolMTLSCertificate) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "agent-pool-mtls-certificates"
}

// AgentPoolMTLSCertificateAttributes holds the attributes for AgentPoolMTLSCertificate (response)
type AgentPoolMTLSCertificateAttributes struct {
	// UTC datetime when the certificate was issued.
	CreatedAt time.Time `json:"created-at"`
	// SHA-256 fingerprint of the certificate as a hex string.
	Fingerprint string `json:"fingerprint"`
	// UTC datetime after which the certificate expires.
	NotValidAfter time.Time `json:"not-valid-after"`
	// Certificate serial number as a hexadecimal string.
	SerialNumber string `json:"serial-number"`
	// Certificate status: active, expired, or revoked.
	Status AgentPoolMTLSCertificateStatus `json:"status"`
}

// AgentPoolMTLSCertificateRelationships holds the relationships for AgentPoolMTLSCertificate (response)
type AgentPoolMTLSCertificateRelationships struct {
	// The account this certificate belongs to.
	Account *Account `json:"account"`
	// The agent pool this certificate belongs to.
	AgentPool *AgentPool `json:"agent-pool"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *AgentPoolMTLSCertificateRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["account"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Account = &Account{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["agent-pool"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.AgentPool = &AgentPool{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *AgentPoolMTLSCertificateRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Account
	if r.Account != nil && r.Account.ID != "" {
		key := r.Account.Type + ":" + r.Account.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Account
			if err := json.Unmarshal(data, &full); err == nil {
				r.Account = &full
			}
		}
	}
	// Populate to-one relationship: AgentPool
	if r.AgentPool != nil && r.AgentPool.ID != "" {
		key := r.AgentPool.Type + ":" + r.AgentPool.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full AgentPool
			if err := json.Unmarshal(data, &full); err == nil {
				r.AgentPool = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// An mTLS client certificate issued for an agent pool. Each certificate is bound to an agent pool and account. Its SHA-256 fingerprint is checked during mTLS enforcement to determine whether an agent connection is accepted. (for requests)
type AgentPoolMTLSCertificateRequest struct {
	ID            string                                       `json:"id,omitempty"`
	Type          string                                       `json:"type,omitempty"`
	Attributes    AgentPoolMTLSCertificateAttributesRequest    `json:"attributes,omitempty"`
	Relationships AgentPoolMTLSCertificateRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r AgentPoolMTLSCertificateRequest) MarshalJSON() ([]byte, error) {
	type Alias AgentPoolMTLSCertificateRequest
	if r.Type == "" {
		r.Type = "agent-pool-mtls-certificates"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r AgentPoolMTLSCertificateRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r AgentPoolMTLSCertificateRequest) GetResourceType() string {
	return "agent-pool-mtls-certificates"
}

// AgentPoolMTLSCertificateAttributesRequest holds the attributes for AgentPoolMTLSCertificate (request)
type AgentPoolMTLSCertificateAttributesRequest struct {
	// UTC datetime when the certificate was issued.
	CreatedAt *value.Value[time.Time] `json:"created-at,omitempty"`
	// SHA-256 fingerprint of the certificate as a hex string.
	Fingerprint *value.Value[string] `json:"fingerprint,omitempty"`
	// UTC datetime after which the certificate expires.
	NotValidAfter *value.Value[time.Time] `json:"not-valid-after,omitempty"`
	// Certificate serial number as a hexadecimal string.
	SerialNumber *value.Value[string] `json:"serial-number,omitempty"`
	// Certificate status: active, expired, or revoked.
	Status *value.Value[AgentPoolMTLSCertificateStatus] `json:"status,omitempty"`
}

// AgentPoolMTLSCertificateRelationshipsRequest holds the relationships for AgentPoolMTLSCertificate (request)
type AgentPoolMTLSCertificateRelationshipsRequest struct {
	// The account this certificate belongs to.
	Account *value.Value[Account] `json:"account,omitempty"`
	// The agent pool this certificate belongs to.
	AgentPool *value.Value[AgentPool] `json:"agent-pool,omitempty"`
}
