// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// AgentDriver represents the type for AgentDriver
// The agent's driver: docker, kubernetes or local.
type AgentDriver string

// AgentDriver constants
const (
	AgentDriverUnknown       AgentDriver = "unknown"
	AgentDriverLocal         AgentDriver = "local"
	AgentDriverDocker        AgentDriver = "docker"
	AgentDriverKubernetes    AgentDriver = "kubernetes"
	AgentDriverKubernetesJob AgentDriver = "kubernetes-job"
)

// AgentUpgradeStatus represents the type for AgentUpgradeStatus
// Agent version upgrade status indicating how current the agent version is and what level of upgrade attention is required. Used to display appropriate warnings and encourage timely upgrades.
type AgentUpgradeStatus string

// AgentUpgradeStatus constants
const (
	AgentUpgradeStatusNone   AgentUpgradeStatus = "none"
	AgentUpgradeStatusLow    AgentUpgradeStatus = "low"
	AgentUpgradeStatusMedium AgentUpgradeStatus = "medium"
	AgentUpgradeStatusHigh   AgentUpgradeStatus = "high"
)

// AgentStatus represents the type for AgentStatus
// The agent's current status * `busy` - The agent is working on a task. * `errored` - The agent has an error and can't operate correctly. The attribute `error-message` has the details. * `idle` - The agent is idle and ready to start working on a task. * `offline` - API server hasn't seen the agent's heartbeat for 30 seconds.
type AgentStatus string

// AgentStatus constants
const (
	AgentStatusIdle    AgentStatus = "idle"
	AgentStatusBusy    AgentStatus = "busy"
	AgentStatusOffline AgentStatus = "offline"
	AgentStatusErrored AgentStatus = "errored"
)

// AgentCpuPlatform represents the type for AgentCpuPlatform
// The agent's CPU platform. The default value is `linux_amd64`.
type AgentCpuPlatform string

// AgentCpuPlatform constants
const (
	AgentCpuPlatformLinuxAmd64 AgentCpuPlatform = "linux_amd64"
	AgentCpuPlatformLinuxArm64 AgentCpuPlatform = "linux_arm64"
)

// AgentKubernetesDriverMode represents the type for AgentKubernetesDriverMode
// The Kubernetes driver mode (default, controller, or worker). Defines the agent's role within the Kubernetes execution model.
type AgentKubernetesDriverMode string

// AgentKubernetesDriverMode constants
const (
	AgentKubernetesDriverModeDefault    AgentKubernetesDriverMode = "default"
	AgentKubernetesDriverModeController AgentKubernetesDriverMode = "controller"
	AgentKubernetesDriverModeWorker     AgentKubernetesDriverMode = "worker"
)

// AgentRuntime represents the type for AgentRuntime
// The agent's runtime (docker, kubernetes, vm, fatgate, etc)
type AgentRuntime string

// AgentRuntime constants
const (
	AgentRuntimeUnknown    AgentRuntime = "unknown"
	AgentRuntimeDocker     AgentRuntime = "docker"
	AgentRuntimeKubernetes AgentRuntime = "kubernetes"
	AgentRuntimeVm         AgentRuntime = "vm"
	AgentRuntimeFargate    AgentRuntime = "fargate"
)

// Response version - used when unmarshalling from API responses
// An agent represents a single instance of self-hosted runner installed on a customer's on-prem infrastructure. An agent resource is automatically created when [self-hosted runner](../../agent_pools.html) connects to the API server to join it [agent pool](agent-pools.html). In order to connect to the pool, the runner requires an [agent pool token](access-tokens.html#create-an-agent-pool-access-token).
type Agent struct {
	ID            string             `json:"id"`
	Type          string             `json:"type"`
	Attributes    AgentAttributes    `json:"attributes"`
	Relationships AgentRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r Agent) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r Agent) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "agents"
}

// AgentAttributes holds the attributes for Agent (response)
type AgentAttributes struct {
	// The agent's CPU platform. The default value is `linux_amd64`.
	CpuPlatform AgentCpuPlatform `json:"cpu-platform"`
	// The resource creation timestamp.
	CreatedAt time.Time `json:"created-at"`
	// The agent's driver: docker, kubernetes or local.
	Driver AgentDriver `json:"driver"`
	// Contains the error message if the agent is in an `errored` status.
	ErrorMessage *string `json:"error-message"`
	// The Kubernetes driver mode (default, controller, or worker). Defines the agent's role within the Kubernetes execution model.
	KubernetesDriverMode AgentKubernetesDriverMode `json:"kubernetes-driver-mode"`
	// The timestamp when the agent was last seen online.
	LastSeenAt time.Time `json:"last-seen-at"`
	// The name of the agent. This must be unique within the agent pool.
	Name string `json:"name"`
	// The agent's OS distribution name and version (ex: `centos_8`, `ubuntu_20`)
	Os string `json:"os"`
	// The UTC datetime of the last relay connect from the Agent.
	RelayLastSeenAt *time.Time `json:"relay-last-seen-at"`
	// The agent's runtime (docker, kubernetes, vm, fatgate, etc)
	Runtime AgentRuntime `json:"runtime"`
	// The agent's current status * `busy` - The agent is working on a task. * `errored` - The agent has an error and can't operate correctly. The attribute `error-message` has the details. * `idle` - The agent is idle and ready to start working on a task. * `offline` - API server hasn't seen the agent's heartbeat for 30 seconds.
	Status AgentStatus `json:"status"`
	// Agent version upgrade status indicating how current the agent version is and what level of upgrade attention is required. Used to display appropriate warnings and encourage timely upgrades.
	UpgradeStatus AgentUpgradeStatus `json:"upgrade-status"`
	// The agent's version.
	Version string `json:"version"`
}

// AgentRelationships holds the relationships for Agent (response)
type AgentRelationships struct {
	// The agent pool this agent is a member of.
	Pool *AgentPool `json:"pool"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *AgentRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["pool"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Pool = &AgentPool{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *AgentRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Pool
	if r.Pool != nil && r.Pool.ID != "" {
		key := r.Pool.Type + ":" + r.Pool.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full AgentPool
			if err := json.Unmarshal(data, &full); err == nil {
				r.Pool = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// An agent represents a single instance of self-hosted runner installed on a customer's on-prem infrastructure. An agent resource is automatically created when [self-hosted runner](../../agent_pools.html) connects to the API server to join it [agent pool](agent-pools.html). In order to connect to the pool, the runner requires an [agent pool token](access-tokens.html#create-an-agent-pool-access-token). (for requests)
type AgentRequest struct {
	ID            string                    `json:"id,omitempty"`
	Type          string                    `json:"type,omitempty"`
	Attributes    AgentAttributesRequest    `json:"attributes,omitempty"`
	Relationships AgentRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r AgentRequest) MarshalJSON() ([]byte, error) {
	type Alias AgentRequest
	if r.Type == "" {
		r.Type = "agents"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r AgentRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r AgentRequest) GetResourceType() string {
	return "agents"
}

// AgentAttributesRequest holds the attributes for Agent (request)
type AgentAttributesRequest struct {
	// The agent's CPU platform. The default value is `linux_amd64`.
	CpuPlatform *value.Value[AgentCpuPlatform] `json:"cpu-platform,omitempty"`
	// The agent's driver: docker, kubernetes or local.
	Driver *value.Value[AgentDriver] `json:"driver,omitempty"`
	// The Kubernetes driver mode (default, controller, or worker). Defines the agent's role within the Kubernetes execution model.
	KubernetesDriverMode *value.Value[AgentKubernetesDriverMode] `json:"kubernetes-driver-mode,omitempty"`
	// The name of the agent. This must be unique within the agent pool.
	Name *value.Value[string] `json:"name,omitempty"`
	// The agent's OS distribution name and version (ex: `centos_8`, `ubuntu_20`)
	Os *value.Value[string] `json:"os,omitempty"`
	// The agent's runtime (docker, kubernetes, vm, fatgate, etc)
	Runtime *value.Value[AgentRuntime] `json:"runtime,omitempty"`
	// The agent's version.
	Version *value.Value[string] `json:"version,omitempty"`
}

// AgentRelationshipsRequest holds the relationships for Agent (request)
type AgentRelationshipsRequest struct {
}
