// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// ContainerImageSyncStatus represents the type for ContainerImageSyncStatus
// Tag synchronization state of the image.
type ContainerImageSyncStatus string

// ContainerImageSyncStatus constants
const (
	ContainerImageSyncStatusPending    ContainerImageSyncStatus = "pending"
	ContainerImageSyncStatusSynced     ContainerImageSyncStatus = "synced"
	ContainerImageSyncStatusFailed     ContainerImageSyncStatus = "failed"
	ContainerImageSyncStatusNoVersions ContainerImageSyncStatus = "no_versions"
)

// ContainerImageVisibility represents the type for ContainerImageVisibility
// Image visibility: a Scalr-managed system image or an account-scoped public custom image.
type ContainerImageVisibility string

// ContainerImageVisibility constants
const (
	ContainerImageVisibilitySystem ContainerImageVisibility = "system"
	ContainerImageVisibilityPublic ContainerImageVisibility = "public"
)

// Response version - used when unmarshalling from API responses

type ContainerImage struct {
	ID            string                      `json:"id"`
	Type          string                      `json:"type"`
	Attributes    ContainerImageAttributes    `json:"attributes"`
	Relationships ContainerImageRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r ContainerImage) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r ContainerImage) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "container-images"
}

// ContainerImageAttributes holds the attributes for ContainerImage (response)
type ContainerImageAttributes struct {
	// The resource creation timestamp.
	CreatedAt time.Time `json:"created-at"`
	// Optional image description.
	Description *string `json:"description"`
	// The timestamp of the last successful synchronization.
	LastSyncedAt *time.Time `json:"last-synced-at"`
	// The container image repository name without a tag, for example scalr/runner.
	Name string `json:"name"`
	// Public OCI registry URL. Defaults to Docker Hub when omitted and cannot be changed after registration.
	RegistryUrl string `json:"registry-url"`
	// Repository path within the registry, without a host, tag, or digest, for example `myorg/runner`. It cannot be changed after registration.
	Repository string `json:"repository"`
	// The last synchronization error, if any.
	SyncError *string `json:"sync-error"`
	// Tag synchronization state of the image.
	SyncStatus ContainerImageSyncStatus `json:"sync-status"`
	// Image visibility: a Scalr-managed system image or an account-scoped public custom image.
	Visibility ContainerImageVisibility `json:"visibility"`
}

// ContainerImageRelationships holds the relationships for ContainerImage (response)
type ContainerImageRelationships struct {
	// The latest version registered for this container image.
	LatestVersion *ContainerImageVersion `json:"latest-version"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *ContainerImageRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["latest-version"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.LatestVersion = &ContainerImageVersion{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *ContainerImageRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: LatestVersion
	if r.LatestVersion != nil && r.LatestVersion.ID != "" {
		key := r.LatestVersion.Type + ":" + r.LatestVersion.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full ContainerImageVersion
			if err := json.Unmarshal(data, &full); err == nil {
				r.LatestVersion = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests

type ContainerImageRequest struct {
	ID            string                             `json:"id,omitempty"`
	Type          string                             `json:"type,omitempty"`
	Attributes    ContainerImageAttributesRequest    `json:"attributes,omitempty"`
	Relationships ContainerImageRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r ContainerImageRequest) MarshalJSON() ([]byte, error) {
	type Alias ContainerImageRequest
	if r.Type == "" {
		r.Type = "container-images"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r ContainerImageRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r ContainerImageRequest) GetResourceType() string {
	return "container-images"
}

// ContainerImageAttributesRequest holds the attributes for ContainerImage (request)
type ContainerImageAttributesRequest struct {
	// Public OCI registry URL. Defaults to Docker Hub when omitted and cannot be changed after registration.
	RegistryUrl *value.Value[string] `json:"registry-url,omitempty"`
	// Repository path within the registry, without a host, tag, or digest, for example `myorg/runner`. It cannot be changed after registration.
	Repository *value.Value[string] `json:"repository,omitempty"`
}

// ContainerImageRelationshipsRequest holds the relationships for ContainerImage (request)
type ContainerImageRelationshipsRequest struct {
}
