// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// A Cost Estimate is the details of the cost estimation phase of a `run` in Scalr. Cost estimation is optional and is enabled/disable per `environment`. If enabled a cost estimation is performed immediately after Terraform plan has completed for every run in every workspace, including dry runs.
type CostEstimate struct {
	ID         string                 `json:"id"`
	Type       string                 `json:"type"`
	Attributes CostEstimateAttributes `json:"attributes"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r CostEstimate) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r CostEstimate) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "cost-estimates"
}

// CostEstimateAttributes holds the attributes for CostEstimate (response)
type CostEstimateAttributes struct {
	// The change in the estimated cost ($) from the previous run (if any).
	DeltaMonthlyCost string `json:"delta-monthly-cost"`
	// When the cost estimate status is `errored`, this field contains the error description.
	ErrorMessage *string `json:"error-message"`
	// The number of resources in the terraform plan, that were included into the estimation. Cost estimation in Scalr supports a number of terraform resources from major [cloud providers](https://docs.scalr.io/docs/cost-estimation)
	MatchedResourcesCount *int `json:"matched-resources-count"`
	// The estimated current monthly cost ($).
	PriorMonthlyCost string `json:"prior-monthly-cost"`
	// The estimated monthly cost ($) if the plan is applied.
	ProposedMonthlyCost string `json:"proposed-monthly-cost"`
	// The total number of resources in the terraform plan.
	ResourcesCount *int `json:"resources-count"`
	// The Cost estimate's current status. Transient states: * `pending` - Cost estimation has been created but not yet `queued`. * `queued` - Queued and waiting for capacity to be available. Final states: * `canceled` - The cost estimate has been canceled. * `errored` - The cost estimate has finished with an error. Attribute `error-message` contains the details. * `finished` - The cost estimate has completed successfully. * `unreachable` - The cost estimate will not run.
	Status string `json:"status"`
	// Date/Time of transition to each status that has occurred.
	StatusTimestamps map[string]interface{} `json:"status-timestamps"`
	// The number of resources in the terraform plan that were excluded from the estimation.
	UnmatchedResourcesCount *int `json:"unmatched-resources-count"`
}

// Request version - used when marshalling for API requests
// A Cost Estimate is the details of the cost estimation phase of a `run` in Scalr. Cost estimation is optional and is enabled/disable per `environment`. If enabled a cost estimation is performed immediately after Terraform plan has completed for every run in every workspace, including dry runs. (for requests)
type CostEstimateRequest struct {
	ID         string                        `json:"id,omitempty"`
	Type       string                        `json:"type,omitempty"`
	Attributes CostEstimateAttributesRequest `json:"attributes,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r CostEstimateRequest) MarshalJSON() ([]byte, error) {
	type Alias CostEstimateRequest
	if r.Type == "" {
		r.Type = "cost-estimates"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r CostEstimateRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r CostEstimateRequest) GetResourceType() string {
	return "cost-estimates"
}

// CostEstimateAttributesRequest holds the attributes for CostEstimate (request)
type CostEstimateAttributesRequest struct {
	// The change in the estimated cost ($) from the previous run (if any).
	DeltaMonthlyCost *value.Value[string] `json:"delta-monthly-cost,omitempty"`
	// When the cost estimate status is `errored`, this field contains the error description.
	ErrorMessage *value.Value[string] `json:"error-message,omitempty"`
	// The number of resources in the terraform plan, that were included into the estimation. Cost estimation in Scalr supports a number of terraform resources from major [cloud providers](https://docs.scalr.io/docs/cost-estimation)
	MatchedResourcesCount *value.Value[int] `json:"matched-resources-count,omitempty"`
	// The estimated current monthly cost ($).
	PriorMonthlyCost *value.Value[string] `json:"prior-monthly-cost,omitempty"`
	// The estimated monthly cost ($) if the plan is applied.
	ProposedMonthlyCost *value.Value[string] `json:"proposed-monthly-cost,omitempty"`
	// The total number of resources in the terraform plan.
	ResourcesCount *value.Value[int] `json:"resources-count,omitempty"`
	// The Cost estimate's current status. Transient states: * `pending` - Cost estimation has been created but not yet `queued`. * `queued` - Queued and waiting for capacity to be available. Final states: * `canceled` - The cost estimate has been canceled. * `errored` - The cost estimate has finished with an error. Attribute `error-message` contains the details. * `finished` - The cost estimate has completed successfully. * `unreachable` - The cost estimate will not run.
	Status *value.Value[string] `json:"status,omitempty"`
	// Date/Time of transition to each status that has occurred.
	StatusTimestamps *value.Value[map[string]interface{}] `json:"status-timestamps,omitempty"`
	// The number of resources in the terraform plan that were excluded from the estimation.
	UnmatchedResourcesCount *value.Value[int] `json:"unmatched-resources-count,omitempty"`
}
