// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// Represents a Webhook Event Definition. Use [List Event Definitions](event-definitions.html#list-event-definitions) to obtain the all Scalr events available for use in webhooks. Then pass a number of the event IDs within `webhook.event` relationship in [Create Webook](webhooks.html#create-webhook) or [Update Webhook](webhooks.html#update-webhook).
type EventDefinition struct {
	ID         string                    `json:"id"`
	Type       string                    `json:"type"`
	Attributes EventDefinitionAttributes `json:"attributes"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r EventDefinition) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r EventDefinition) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "event-definitions"
}

// EventDefinitionAttributes holds the attributes for EventDefinition (response)
type EventDefinitionAttributes struct {
	// The event details.
	Description string `json:"description"`
	// The name of the event.
	Name string `json:"name"`
}

// Request version - used when marshalling for API requests
// Represents a Webhook Event Definition. Use [List Event Definitions](event-definitions.html#list-event-definitions) to obtain the all Scalr events available for use in webhooks. Then pass a number of the event IDs within `webhook.event` relationship in [Create Webook](webhooks.html#create-webhook) or [Update Webhook](webhooks.html#update-webhook). (for requests)
type EventDefinitionRequest struct {
	ID         string                           `json:"id,omitempty"`
	Type       string                           `json:"type,omitempty"`
	Attributes EventDefinitionAttributesRequest `json:"attributes,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r EventDefinitionRequest) MarshalJSON() ([]byte, error) {
	type Alias EventDefinitionRequest
	if r.Type == "" {
		r.Type = "event-definitions"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r EventDefinitionRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r EventDefinitionRequest) GetResourceType() string {
	return "event-definitions"
}

// EventDefinitionAttributesRequest holds the attributes for EventDefinition (request)
type EventDefinitionAttributesRequest struct {
	// The event details.
	Description *value.Value[string] `json:"description,omitempty"`
	// The name of the event.
	Name *value.Value[string] `json:"name,omitempty"`
}
