// Code generated by scalr-gen. DO NOT EDIT.

package schemas

// Describes JSON:API generic Resource Identifier object. see https://jsonapi.org/format/#document-resource-identifier-objects
type FederatedEnvironmentRelationship struct {
	Type string `json:"type,omitempty"`
	Id   string `json:"id,omitempty"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r FederatedEnvironmentRelationship) GetID() string {
	return r.Id
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r FederatedEnvironmentRelationship) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "environments"
}
