// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// A policy provides details of a single OPA policy as declared in [scalr-policy.hcl](../../opa.html#creating-policy-groups).
type Policy struct {
	ID            string              `json:"id"`
	Type          string              `json:"type"`
	Attributes    PolicyAttributes    `json:"attributes"`
	Relationships PolicyRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r Policy) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r Policy) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "policies"
}

// PolicyAttributes holds the attributes for Policy (response)
type PolicyAttributes struct {
	// If set to `false`, the policy will not be evaluated during a run.
	Enabled bool `json:"enabled"`
	// The policy's enforcement level. * `hard-mandatory` - cannot be overridden. * `soft-mandatory` - can be overridden through an approval by account admins and other authorized roles. * `advisory` - provides a warning only.
	EnforcedLevel string `json:"enforced-level"`
	// The name of the policy.
	Name string `json:"name"`
}

// PolicyRelationships holds the relationships for Policy (response)
type PolicyRelationships struct {
	// The policy group this policy belongs to.
	PolicyGroup *PolicyGroup `json:"policy-group"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *PolicyRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["policy-group"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.PolicyGroup = &PolicyGroup{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *PolicyRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: PolicyGroup
	if r.PolicyGroup != nil && r.PolicyGroup.ID != "" {
		key := r.PolicyGroup.Type + ":" + r.PolicyGroup.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full PolicyGroup
			if err := json.Unmarshal(data, &full); err == nil {
				r.PolicyGroup = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// A policy provides details of a single OPA policy as declared in [scalr-policy.hcl](../../opa.html#creating-policy-groups). (for requests)
type PolicyRequest struct {
	ID            string                     `json:"id,omitempty"`
	Type          string                     `json:"type,omitempty"`
	Attributes    PolicyAttributesRequest    `json:"attributes,omitempty"`
	Relationships PolicyRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r PolicyRequest) MarshalJSON() ([]byte, error) {
	type Alias PolicyRequest
	if r.Type == "" {
		r.Type = "policies"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r PolicyRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r PolicyRequest) GetResourceType() string {
	return "policies"
}

// PolicyAttributesRequest holds the attributes for Policy (request)
type PolicyAttributesRequest struct {
	// The name of the policy.
	Name *value.Value[string] `json:"name,omitempty"`
}

// PolicyRelationshipsRequest holds the relationships for Policy (request)
type PolicyRelationshipsRequest struct {
}
