// Code generated by scalr-gen. DO NOT EDIT.

package schemas

type PolicyGroupEnvironmentRelationship struct {
	Type string `json:"type,omitempty"`
	Id   string `json:"id,omitempty"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r PolicyGroupEnvironmentRelationship) GetID() string {
	return r.Id
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r PolicyGroupEnvironmentRelationship) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "environments"
}
