// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// The provider configuration link attaches the provider configuration to an environment or workspace.
type ProviderConfigurationLink struct {
	ID            string                                 `json:"id"`
	Type          string                                 `json:"type"`
	Attributes    ProviderConfigurationLinkAttributes    `json:"attributes"`
	Relationships ProviderConfigurationLinkRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r ProviderConfigurationLink) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r ProviderConfigurationLink) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "provider-configuration-links"
}

// ProviderConfigurationLinkAttributes holds the attributes for ProviderConfigurationLink (response)
type ProviderConfigurationLinkAttributes struct {
	// Is used only for the workspace links. Meta-argument for using the same provider with different configurations for different resources.
	Alias string `json:"alias"`
	// Is used only for the environment links. Indicates whether the provider configuration must be used in every environment workspace during runs without direct linking. This behaviour can be changed in specific workspace by creating direct workspace link without alias.
	Default bool `json:"default"`
}

// ProviderConfigurationLinkRelationships holds the relationships for ProviderConfigurationLink (response)
type ProviderConfigurationLinkRelationships struct {
	Environment           *Environment           `json:"environment"`
	ProviderConfiguration *ProviderConfiguration `json:"provider-configuration"`
	Workspace             *Workspace             `json:"workspace"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *ProviderConfigurationLinkRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["environment"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Environment = &Environment{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["provider-configuration"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.ProviderConfiguration = &ProviderConfiguration{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["workspace"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Workspace = &Workspace{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *ProviderConfigurationLinkRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Environment
	if r.Environment != nil && r.Environment.ID != "" {
		key := r.Environment.Type + ":" + r.Environment.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Environment
			if err := json.Unmarshal(data, &full); err == nil {
				r.Environment = &full
			}
		}
	}
	// Populate to-one relationship: ProviderConfiguration
	if r.ProviderConfiguration != nil && r.ProviderConfiguration.ID != "" {
		key := r.ProviderConfiguration.Type + ":" + r.ProviderConfiguration.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full ProviderConfiguration
			if err := json.Unmarshal(data, &full); err == nil {
				r.ProviderConfiguration = &full
			}
		}
	}
	// Populate to-one relationship: Workspace
	if r.Workspace != nil && r.Workspace.ID != "" {
		key := r.Workspace.Type + ":" + r.Workspace.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Workspace
			if err := json.Unmarshal(data, &full); err == nil {
				r.Workspace = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// The provider configuration link attaches the provider configuration to an environment or workspace. (for requests)
type ProviderConfigurationLinkRequest struct {
	ID            string                                        `json:"id,omitempty"`
	Type          string                                        `json:"type,omitempty"`
	Attributes    ProviderConfigurationLinkAttributesRequest    `json:"attributes,omitempty"`
	Relationships ProviderConfigurationLinkRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r ProviderConfigurationLinkRequest) MarshalJSON() ([]byte, error) {
	type Alias ProviderConfigurationLinkRequest
	if r.Type == "" {
		r.Type = "provider-configuration-links"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r ProviderConfigurationLinkRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r ProviderConfigurationLinkRequest) GetResourceType() string {
	return "provider-configuration-links"
}

// ProviderConfigurationLinkAttributesRequest holds the attributes for ProviderConfigurationLink (request)
type ProviderConfigurationLinkAttributesRequest struct {
	// Is used only for the workspace links. Meta-argument for using the same provider with different configurations for different resources.
	Alias *value.Value[string] `json:"alias,omitempty"`
}

// ProviderConfigurationLinkRelationshipsRequest holds the relationships for ProviderConfigurationLink (request)
type ProviderConfigurationLinkRelationshipsRequest struct {
	ProviderConfiguration *value.Value[ProviderConfiguration] `json:"provider-configuration,omitempty"`
}
