// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// The Terraform Registry Provider resource.
type Provider struct {
	ID            string                `json:"id"`
	Type          string                `json:"type"`
	Attributes    ProviderAttributes    `json:"attributes"`
	Relationships ProviderRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r Provider) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r Provider) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "providers"
}

// ProviderAttributes holds the attributes for Provider (response)
type ProviderAttributes struct {
	// The description of the provider.
	Description *string `json:"description"`
	// The name of the provider.
	Name string `json:"name"`
	// The namespace this provider belongs to.
	Namespace string `json:"namespace"`
}

// ProviderRelationships holds the relationships for Provider (response)
type ProviderRelationships struct {
	// The latest version of the provider in any status.
	LatestProviderVersion *ProviderVersion `json:"latest-provider-version"`
	// The latest uploaded version of the provider.
	ProviderVersion *ProviderVersion `json:"provider-version"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *ProviderRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["latest-provider-version"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.LatestProviderVersion = &ProviderVersion{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["provider-version"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.ProviderVersion = &ProviderVersion{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *ProviderRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: LatestProviderVersion
	if r.LatestProviderVersion != nil && r.LatestProviderVersion.ID != "" {
		key := r.LatestProviderVersion.Type + ":" + r.LatestProviderVersion.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full ProviderVersion
			if err := json.Unmarshal(data, &full); err == nil {
				r.LatestProviderVersion = &full
			}
		}
	}
	// Populate to-one relationship: ProviderVersion
	if r.ProviderVersion != nil && r.ProviderVersion.ID != "" {
		key := r.ProviderVersion.Type + ":" + r.ProviderVersion.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full ProviderVersion
			if err := json.Unmarshal(data, &full); err == nil {
				r.ProviderVersion = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// The Terraform Registry Provider resource. (for requests)
type ProviderRequest struct {
	ID            string                       `json:"id,omitempty"`
	Type          string                       `json:"type,omitempty"`
	Attributes    ProviderAttributesRequest    `json:"attributes,omitempty"`
	Relationships ProviderRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r ProviderRequest) MarshalJSON() ([]byte, error) {
	type Alias ProviderRequest
	if r.Type == "" {
		r.Type = "providers"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r ProviderRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r ProviderRequest) GetResourceType() string {
	return "providers"
}

// ProviderAttributesRequest holds the attributes for Provider (request)
type ProviderAttributesRequest struct {
	// The description of the provider.
	Description *value.Value[string] `json:"description,omitempty"`
	// The name of the provider.
	Name *value.Value[string] `json:"name,omitempty"`
}

// ProviderRelationshipsRequest holds the relationships for Provider (request)
type ProviderRelationshipsRequest struct {
}
