// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// ProviderVersionStatus represents the type for ProviderVersionStatus
// The provider version's current status.
type ProviderVersionStatus string

// ProviderVersionStatus constants
const (
	ProviderVersionStatusPending  ProviderVersionStatus = "pending"
	ProviderVersionStatusUploaded ProviderVersionStatus = "uploaded"
	ProviderVersionStatusErrored  ProviderVersionStatus = "errored"
)

// Response version - used when unmarshalling from API responses
// The Terraform Registry Provider Version resource.
type ProviderVersion struct {
	ID            string                       `json:"id"`
	Type          string                       `json:"type"`
	Attributes    ProviderVersionAttributes    `json:"attributes"`
	Relationships ProviderVersionRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r ProviderVersion) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r ProviderVersion) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "provider-versions"
}

// ProviderVersionAttributes holds the attributes for ProviderVersion (response)
type ProviderVersionAttributes struct {
	// The email of the user who added the provider version.
	CreatedByEmail *string `json:"created-by-email"`
	// The error description when this provider version's status is `errored`.
	ErrorMessage *string `json:"error-message"`
	// The timestamp when the provider version was released.
	ReleasedAt *time.Time `json:"released-at"`
	// A blob size in bytes.
	Size *int `json:"size"`
	// The provider version's current status.
	Status ProviderVersionStatus `json:"status"`
	// Semantic version.
	Version string `json:"version"`
}

// ProviderVersionRelationships holds the relationships for ProviderVersion (response)
type ProviderVersionRelationships struct {
	// The GPG key used to verify the signature of the provider version.
	GpgKey *GPGKey `json:"gpg-key"`
	// The provider that the provider version belongs to.
	Provider *Provider `json:"provider"`
	// The README of the provider version.
	Readme *ProviderReadme `json:"readme"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *ProviderVersionRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["gpg-key"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.GpgKey = &GPGKey{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["provider"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Provider = &Provider{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["readme"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Readme = &ProviderReadme{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *ProviderVersionRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: GpgKey
	if r.GpgKey != nil && r.GpgKey.ID != "" {
		key := r.GpgKey.Type + ":" + r.GpgKey.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full GPGKey
			if err := json.Unmarshal(data, &full); err == nil {
				r.GpgKey = &full
			}
		}
	}
	// Populate to-one relationship: Provider
	if r.Provider != nil && r.Provider.ID != "" {
		key := r.Provider.Type + ":" + r.Provider.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Provider
			if err := json.Unmarshal(data, &full); err == nil {
				r.Provider = &full
			}
		}
	}
	// Populate to-one relationship: Readme
	if r.Readme != nil && r.Readme.ID != "" {
		key := r.Readme.Type + ":" + r.Readme.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full ProviderReadme
			if err := json.Unmarshal(data, &full); err == nil {
				r.Readme = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// The Terraform Registry Provider Version resource. (for requests)
type ProviderVersionRequest struct {
	ID            string                              `json:"id,omitempty"`
	Type          string                              `json:"type,omitempty"`
	Attributes    ProviderVersionAttributesRequest    `json:"attributes,omitempty"`
	Relationships ProviderVersionRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r ProviderVersionRequest) MarshalJSON() ([]byte, error) {
	type Alias ProviderVersionRequest
	if r.Type == "" {
		r.Type = "provider-versions"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r ProviderVersionRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r ProviderVersionRequest) GetResourceType() string {
	return "provider-versions"
}

// ProviderVersionAttributesRequest holds the attributes for ProviderVersion (request)
type ProviderVersionAttributesRequest struct {
	// Semantic version.
	Version *value.Value[string] `json:"version,omitempty"`
}

// ProviderVersionRelationshipsRequest holds the relationships for ProviderVersion (request)
type ProviderVersionRelationshipsRequest struct {
	// The GPG key used to verify the signature of the provider version.
	GpgKey *value.Value[GPGKey] `json:"gpg-key,omitempty"`
	// The provider that the provider version belongs to.
	Provider *value.Value[Provider] `json:"provider,omitempty"`
}
