// Code generated by scalr-gen. DO NOT EDIT.

package schemas

// Represents remote state consumers' relationship.
type RemoteStateConsumerRelationship struct {
	Type string `json:"type,omitempty"`
	Id   string `json:"id,omitempty"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r RemoteStateConsumerRelationship) GetID() string {
	return r.Id
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r RemoteStateConsumerRelationship) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "workspaces"
}
