// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// Run triggers allow runs to queue automatically in downstream workspace on successful apply of runs in any of the upstream workspaces.
type RunTrigger struct {
	ID            string                  `json:"id"`
	Type          string                  `json:"type"`
	Attributes    RunTriggerAttributes    `json:"attributes"`
	Relationships RunTriggerRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r RunTrigger) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r RunTrigger) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "run-triggers"
}

// RunTriggerAttributes holds the attributes for RunTrigger (response)
type RunTriggerAttributes struct {
	// The resource creation timestamp.
	CreatedAt time.Time `json:"created-at"`
}

// RunTriggerRelationships holds the relationships for RunTrigger (response)
type RunTriggerRelationships struct {
	// Downstream workspace in which new runs will be created.
	Downstream *Workspace `json:"downstream"`
	// Upstream workspace to track new runs.
	Upstream *Workspace `json:"upstream"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *RunTriggerRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["downstream"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Downstream = &Workspace{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["upstream"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Upstream = &Workspace{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *RunTriggerRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Downstream
	if r.Downstream != nil && r.Downstream.ID != "" {
		key := r.Downstream.Type + ":" + r.Downstream.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Workspace
			if err := json.Unmarshal(data, &full); err == nil {
				r.Downstream = &full
			}
		}
	}
	// Populate to-one relationship: Upstream
	if r.Upstream != nil && r.Upstream.ID != "" {
		key := r.Upstream.Type + ":" + r.Upstream.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Workspace
			if err := json.Unmarshal(data, &full); err == nil {
				r.Upstream = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// Run triggers allow runs to queue automatically in downstream workspace on successful apply of runs in any of the upstream workspaces. (for requests)
type RunTriggerRequest struct {
	ID            string                         `json:"id,omitempty"`
	Type          string                         `json:"type,omitempty"`
	Attributes    RunTriggerAttributesRequest    `json:"attributes,omitempty"`
	Relationships RunTriggerRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r RunTriggerRequest) MarshalJSON() ([]byte, error) {
	type Alias RunTriggerRequest
	if r.Type == "" {
		r.Type = "run-triggers"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r RunTriggerRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r RunTriggerRequest) GetResourceType() string {
	return "run-triggers"
}

// RunTriggerAttributesRequest holds the attributes for RunTrigger (request)
type RunTriggerAttributesRequest struct {
}

// RunTriggerRelationshipsRequest holds the relationships for RunTrigger (request)
type RunTriggerRelationshipsRequest struct {
	// Downstream workspace in which new runs will be created.
	Downstream *value.Value[Workspace] `json:"downstream,omitempty"`
	// Upstream workspace to track new runs.
	Upstream *value.Value[Workspace] `json:"upstream,omitempty"`
}
