// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// Tag is a keyword or term associated with a Scalr resource. It is used to label resources across the account to help to identify them, improve searchability or can even participate in a terraform run e.g. as a part of metadata for policy decision. Tags are unique within the account. Deleted tags will be removed from associated resources.
type Tag struct {
	ID            string           `json:"id"`
	Type          string           `json:"type"`
	Attributes    TagAttributes    `json:"attributes"`
	Relationships TagRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r Tag) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r Tag) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "tags"
}

// TagAttributes holds the attributes for Tag (response)
type TagAttributes struct {
	// The name of the tag. It must be unique within the account.
	Name string `json:"name"`
}

// TagRelationships holds the relationships for Tag (response)
type TagRelationships struct {
	// The account this tag belongs to.
	Account *Account `json:"account"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *TagRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["account"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Account = &Account{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *TagRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Account
	if r.Account != nil && r.Account.ID != "" {
		key := r.Account.Type + ":" + r.Account.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Account
			if err := json.Unmarshal(data, &full); err == nil {
				r.Account = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// Tag is a keyword or term associated with a Scalr resource. It is used to label resources across the account to help to identify them, improve searchability or can even participate in a terraform run e.g. as a part of metadata for policy decision. Tags are unique within the account. Deleted tags will be removed from associated resources. (for requests)
type TagRequest struct {
	ID            string                  `json:"id,omitempty"`
	Type          string                  `json:"type,omitempty"`
	Attributes    TagAttributesRequest    `json:"attributes,omitempty"`
	Relationships TagRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r TagRequest) MarshalJSON() ([]byte, error) {
	type Alias TagRequest
	if r.Type == "" {
		r.Type = "tags"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r TagRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r TagRequest) GetResourceType() string {
	return "tags"
}

// TagAttributesRequest holds the attributes for Tag (request)
type TagAttributesRequest struct {
	// The name of the tag. It must be unique within the account.
	Name *value.Value[string] `json:"name,omitempty"`
}

// TagRelationshipsRequest holds the relationships for Tag (request)
type TagRelationshipsRequest struct {
}
