// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// Represents terraform provider version usage.
type TerraformProviderVersionUsage struct {
	ID            string                                     `json:"id"`
	Type          string                                     `json:"type"`
	Attributes    TerraformProviderVersionUsageAttributes    `json:"attributes"`
	Relationships TerraformProviderVersionUsageRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r TerraformProviderVersionUsage) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r TerraformProviderVersionUsage) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "tf-provider-version-usages"
}

// TerraformProviderVersionUsageAttributes holds the attributes for TerraformProviderVersionUsage (response)
type TerraformProviderVersionUsageAttributes struct {
	CreatedAt time.Time `json:"created-at"`
	Version   *string   `json:"version"`
}

// TerraformProviderVersionUsageRelationships holds the relationships for TerraformProviderVersionUsage (response)
type TerraformProviderVersionUsageRelationships struct {
	// The environment this usage instance belongs to.
	Environment *Environment `json:"environment"`
	// The workspace this usage belongs to.
	Workspace *Workspace `json:"workspace"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *TerraformProviderVersionUsageRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["environment"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Environment = &Environment{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["workspace"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Workspace = &Workspace{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *TerraformProviderVersionUsageRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Environment
	if r.Environment != nil && r.Environment.ID != "" {
		key := r.Environment.Type + ":" + r.Environment.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Environment
			if err := json.Unmarshal(data, &full); err == nil {
				r.Environment = &full
			}
		}
	}
	// Populate to-one relationship: Workspace
	if r.Workspace != nil && r.Workspace.ID != "" {
		key := r.Workspace.Type + ":" + r.Workspace.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Workspace
			if err := json.Unmarshal(data, &full); err == nil {
				r.Workspace = &full
			}
		}
	}
}

// Request version - used when marshalling for API requests
// Represents terraform provider version usage. (for requests)
type TerraformProviderVersionUsageRequest struct {
	ID            string                                            `json:"id,omitempty"`
	Type          string                                            `json:"type,omitempty"`
	Attributes    TerraformProviderVersionUsageAttributesRequest    `json:"attributes,omitempty"`
	Relationships TerraformProviderVersionUsageRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r TerraformProviderVersionUsageRequest) MarshalJSON() ([]byte, error) {
	type Alias TerraformProviderVersionUsageRequest
	if r.Type == "" {
		r.Type = "tf-provider-version-usages"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r TerraformProviderVersionUsageRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r TerraformProviderVersionUsageRequest) GetResourceType() string {
	return "tf-provider-version-usages"
}

// TerraformProviderVersionUsageAttributesRequest holds the attributes for TerraformProviderVersionUsage (request)
type TerraformProviderVersionUsageAttributesRequest struct {
	CreatedAt *value.Value[time.Time] `json:"created-at,omitempty"`
	Version   *value.Value[string]    `json:"version,omitempty"`
}

// TerraformProviderVersionUsageRelationshipsRequest holds the relationships for TerraformProviderVersionUsage (request)
type TerraformProviderVersionUsageRelationshipsRequest struct {
	// The environment this usage instance belongs to.
	Environment *value.Value[Environment] `json:"environment,omitempty"`
	// The workspace this usage belongs to.
	Workspace *value.Value[Workspace] `json:"workspace,omitempty"`
}
