// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// Represents terraform provider usage instance.
type TerraformProviderUsage struct {
	ID         string                           `json:"id"`
	Type       string                           `json:"type"`
	Attributes TerraformProviderUsageAttributes `json:"attributes"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r TerraformProviderUsage) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r TerraformProviderUsage) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "tf-provider-usages"
}

// TerraformProviderUsageAttributes holds the attributes for TerraformProviderUsage (response)
type TerraformProviderUsageAttributes struct {
	Provider          string `json:"provider"`
	Source            string `json:"source"`
	VersionsUsedCount int    `json:"versions-used-count"`
	WorkspacesCount   int    `json:"workspaces-count"`
}

// Request version - used when marshalling for API requests
// Represents terraform provider usage instance. (for requests)
type TerraformProviderUsageRequest struct {
	ID         string                                  `json:"id,omitempty"`
	Type       string                                  `json:"type,omitempty"`
	Attributes TerraformProviderUsageAttributesRequest `json:"attributes,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r TerraformProviderUsageRequest) MarshalJSON() ([]byte, error) {
	type Alias TerraformProviderUsageRequest
	if r.Type == "" {
		r.Type = "tf-provider-usages"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r TerraformProviderUsageRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r TerraformProviderUsageRequest) GetResourceType() string {
	return "tf-provider-usages"
}

// TerraformProviderUsageAttributesRequest holds the attributes for TerraformProviderUsage (request)
type TerraformProviderUsageAttributesRequest struct {
	Provider          *value.Value[string] `json:"provider,omitempty"`
	Source            *value.Value[string] `json:"source,omitempty"`
	VersionsUsedCount *value.Value[int]    `json:"versions-used-count,omitempty"`
	WorkspacesCount   *value.Value[int]    `json:"workspaces-count,omitempty"`
}
