// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// A named container of variables. Variable sets can be granted access to environments and applied to workspaces.
type VariableSet struct {
	ID            string                   `json:"id"`
	Type          string                   `json:"type"`
	Attributes    VariableSetAttributes    `json:"attributes"`
	Relationships VariableSetRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r VariableSet) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r VariableSet) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "var-sets"
}

// VariableSetAttributes holds the attributes for VariableSet (response)
type VariableSetAttributes struct {
	// Optional description of the variable set.
	Description *string `json:"description"`
	// If true, the variable set is available in all current and future environments of the account without explicitly linking it to each environment.
	IsShared bool `json:"is-shared"`
	// The name of the variable set. Unique within an account.
	Name string `json:"name"`
	// The UTC timestamp of the last update to this variable set.
	UpdatedAt time.Time `json:"updated-at"`
	// The email of the user who last updated this variable set.
	UpdatedByEmail *string `json:"updated-by-email"`
}

// VariableSetRelationships holds the relationships for VariableSet (response)
type VariableSetRelationships struct {
	// The account this variable set belongs to.
	Account *Account `json:"account"`
	// The list of environments this integration is directly linked to.
	Environments []*Environment `json:"environments"`
	// The teams this variable set belongs to.
	Owners []*Team `json:"owners"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *VariableSetRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["account"]; ok {
		// To-one relationship
		var rel struct {
			Data *struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Account = &Account{
				ID:   rel.Data.ID,
				Type: rel.Data.Type,
			}
		}
	}
	if raw, ok := temp["environments"]; ok {
		// To-many relationship
		var rel struct {
			Data []struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Environments = make([]*Environment, len(rel.Data))
			for i, d := range rel.Data {
				r.Environments[i] = &Environment{
					ID:   d.ID,
					Type: d.Type,
				}
			}
		}
	}
	if raw, ok := temp["owners"]; ok {
		// To-many relationship
		var rel struct {
			Data []struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.Owners = make([]*Team, len(rel.Data))
			for i, d := range rel.Data {
				r.Owners[i] = &Team{
					ID:   d.ID,
					Type: d.Type,
				}
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *VariableSetRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-one relationship: Account
	if r.Account != nil && r.Account.ID != "" {
		key := r.Account.Type + ":" + r.Account.ID
		if fullResource, ok := includedMap[key]; ok {
			// Unmarshal the full resource
			data, _ := json.Marshal(fullResource)
			var full Account
			if err := json.Unmarshal(data, &full); err == nil {
				r.Account = &full
			}
		}
	}
	// Populate to-many relationship: Environments
	if r.Environments != nil {
		for i, resource := range r.Environments {
			if resource != nil && resource.ID != "" {
				key := resource.Type + ":" + resource.ID
				if fullResource, ok := includedMap[key]; ok {
					// Unmarshal the full resource
					data, _ := json.Marshal(fullResource)
					var full Environment
					if err := json.Unmarshal(data, &full); err == nil {
						r.Environments[i] = &full
					}
				}
			}
		}
	}
	// Populate to-many relationship: Owners
	if r.Owners != nil {
		for i, resource := range r.Owners {
			if resource != nil && resource.ID != "" {
				key := resource.Type + ":" + resource.ID
				if fullResource, ok := includedMap[key]; ok {
					// Unmarshal the full resource
					data, _ := json.Marshal(fullResource)
					var full Team
					if err := json.Unmarshal(data, &full); err == nil {
						r.Owners[i] = &full
					}
				}
			}
		}
	}
}

// Request version - used when marshalling for API requests
// A named container of variables. Variable sets can be granted access to environments and applied to workspaces. (for requests)
type VariableSetRequest struct {
	ID            string                          `json:"id,omitempty"`
	Type          string                          `json:"type,omitempty"`
	Attributes    VariableSetAttributesRequest    `json:"attributes,omitempty"`
	Relationships VariableSetRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r VariableSetRequest) MarshalJSON() ([]byte, error) {
	type Alias VariableSetRequest
	if r.Type == "" {
		r.Type = "var-sets"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r VariableSetRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r VariableSetRequest) GetResourceType() string {
	return "var-sets"
}

// VariableSetAttributesRequest holds the attributes for VariableSet (request)
type VariableSetAttributesRequest struct {
	// Optional description of the variable set.
	Description *value.Value[string] `json:"description,omitempty"`
	// If true, the variable set is available in all current and future environments of the account without explicitly linking it to each environment.
	IsShared *value.Value[bool] `json:"is-shared,omitempty"`
	// The name of the variable set. Unique within an account.
	Name *value.Value[string] `json:"name,omitempty"`
}

// VariableSetRelationshipsRequest holds the relationships for VariableSet (request)
type VariableSetRelationshipsRequest struct {
	// The list of environments this integration is directly linked to.
	Environments *value.Value[[]Environment] `json:"environments,omitempty"`
	// The teams this variable set belongs to.
	Owners *value.Value[[]Team] `json:"owners,omitempty"`
}
