// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// WorkloadIdentityProviderStatus represents the type for WorkloadIdentityProviderStatus
// The status of the workload identity provider.
type WorkloadIdentityProviderStatus string

// WorkloadIdentityProviderStatus constants
const (
	WorkloadIdentityProviderStatusPending                 WorkloadIdentityProviderStatus = "pending"
	WorkloadIdentityProviderStatusActive                  WorkloadIdentityProviderStatus = "active"
	WorkloadIdentityProviderStatusInvalidProviderSettings WorkloadIdentityProviderStatus = "invalid_provider_settings"
	WorkloadIdentityProviderStatusFetchJwksError          WorkloadIdentityProviderStatus = "fetch_jwks_error"
	WorkloadIdentityProviderStatusNotSupportedJwks        WorkloadIdentityProviderStatus = "not_supported_jwks"
	WorkloadIdentityProviderStatusInternalError           WorkloadIdentityProviderStatus = "internal_error"
)

// Response version - used when unmarshalling from API responses
// External OpenID Connect 1.0 compliant identity provider.
type WorkloadIdentityProvider struct {
	ID            string                                `json:"id"`
	Type          string                                `json:"type"`
	Attributes    WorkloadIdentityProviderAttributes    `json:"attributes"`
	Relationships WorkloadIdentityProviderRelationships `json:"relationships"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r WorkloadIdentityProvider) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r WorkloadIdentityProvider) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "workload-identity-providers"
}

// WorkloadIdentityProviderAttributes holds the attributes for WorkloadIdentityProvider (response)
type WorkloadIdentityProviderAttributes struct {
	// A list of audiences allowed for the IdP tokens.
	AllowedAudiences []string `json:"allowed-audiences"`
	// The UTC datetime at which the workload identity provider was created.
	CreatedAt time.Time `json:"created-at"`
	// Email of the user who created workload identity provider.
	CreatedByEmail *string `json:"created-by-email"`
	// The name of the workload identity provider.
	Name string `json:"name"`
	// The status of the workload identity provider.
	Status WorkloadIdentityProviderStatus `json:"status"`
	// The publicly available URL of the IdP (must start with "https://", not include a port number and not end with a trailing slash).
	Url string `json:"url"`
}

// WorkloadIdentityProviderRelationships holds the relationships for WorkloadIdentityProvider (response)
type WorkloadIdentityProviderRelationships struct {
	AssumeServiceAccountPolicies []*AssumeServiceAccountPolicy `json:"assume-service-account-policies"`
}

// UnmarshalJSON implements custom unmarshalling for relationships
func (r *WorkloadIdentityProviderRelationships) UnmarshalJSON(data []byte) error {
	// Parse into temporary structure that matches JSON:API format
	var temp map[string]json.RawMessage
	if err := json.Unmarshal(data, &temp); err != nil {
		return err
	}

	if raw, ok := temp["assume-service-account-policies"]; ok {
		// To-many relationship
		var rel struct {
			Data []struct {
				ID   string `json:"id"`
				Type string `json:"type"`
			} `json:"data"`
		}
		if err := json.Unmarshal(raw, &rel); err != nil {
			return err
		}
		if rel.Data != nil {
			r.AssumeServiceAccountPolicies = make([]*AssumeServiceAccountPolicy, len(rel.Data))
			for i, d := range rel.Data {
				r.AssumeServiceAccountPolicies[i] = &AssumeServiceAccountPolicy{
					ID:   d.ID,
					Type: d.Type,
				}
			}
		}
	}
	return nil
}

// PopulateIncludes merges included resources into the relationships
func (r *WorkloadIdentityProviderRelationships) PopulateIncludes(included []map[string]interface{}) {
	if r == nil || len(included) == 0 {
		return
	}

	// Build a map of included resources by type+id for fast lookup
	includedMap := make(map[string]map[string]interface{})
	for _, inc := range included {
		if id, ok := inc["id"].(string); ok {
			if typ, ok := inc["type"].(string); ok {
				key := typ + ":" + id
				includedMap[key] = inc
			}
		}
	}

	// Populate to-many relationship: AssumeServiceAccountPolicies
	if r.AssumeServiceAccountPolicies != nil {
		for i, resource := range r.AssumeServiceAccountPolicies {
			if resource != nil && resource.ID != "" {
				key := resource.Type + ":" + resource.ID
				if fullResource, ok := includedMap[key]; ok {
					// Unmarshal the full resource
					data, _ := json.Marshal(fullResource)
					var full AssumeServiceAccountPolicy
					if err := json.Unmarshal(data, &full); err == nil {
						r.AssumeServiceAccountPolicies[i] = &full
					}
				}
			}
		}
	}
}

// Request version - used when marshalling for API requests
// External OpenID Connect 1.0 compliant identity provider. (for requests)
type WorkloadIdentityProviderRequest struct {
	ID            string                                       `json:"id,omitempty"`
	Type          string                                       `json:"type,omitempty"`
	Attributes    WorkloadIdentityProviderAttributesRequest    `json:"attributes,omitempty"`
	Relationships WorkloadIdentityProviderRelationshipsRequest `json:"relationships,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r WorkloadIdentityProviderRequest) MarshalJSON() ([]byte, error) {
	type Alias WorkloadIdentityProviderRequest
	if r.Type == "" {
		r.Type = "workload-identity-providers"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r WorkloadIdentityProviderRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r WorkloadIdentityProviderRequest) GetResourceType() string {
	return "workload-identity-providers"
}

// WorkloadIdentityProviderAttributesRequest holds the attributes for WorkloadIdentityProvider (request)
type WorkloadIdentityProviderAttributesRequest struct {
	// A list of audiences allowed for the IdP tokens.
	AllowedAudiences *value.Value[[]string] `json:"allowed-audiences,omitempty"`
	// The name of the workload identity provider.
	Name *value.Value[string] `json:"name,omitempty"`
	// The publicly available URL of the IdP (must start with "https://", not include a port number and not end with a trailing slash).
	Url *value.Value[string] `json:"url,omitempty"`
}

// WorkloadIdentityProviderRelationshipsRequest holds the relationships for WorkloadIdentityProvider (request)
type WorkloadIdentityProviderRelationshipsRequest struct {
}
