// Code generated by scalr-gen. DO NOT EDIT.

package schemas

import (
	"encoding/json"
	"time"

	"github.com/scalr/go-scalr/v2/scalr/value"
)

// Response version - used when unmarshalling from API responses
// A WorkspaceReadme resource represents the readme file for a workspace.
type WorkspaceReadme struct {
	ID         string                    `json:"id"`
	Type       string                    `json:"type"`
	Attributes WorkspaceReadmeAttributes `json:"attributes"`
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r WorkspaceReadme) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r WorkspaceReadme) GetResourceType() string {
	if r.Type != "" {
		return r.Type
	}
	return "workspace-readme"
}

// WorkspaceReadmeAttributes holds the attributes for WorkspaceReadme (response)
type WorkspaceReadmeAttributes struct {
	// The content of the readme file.
	Content string `json:"content"`
	// The time when the readme record was created.
	CreatedAt time.Time `json:"created-at"`
}

// Request version - used when marshalling for API requests
// A WorkspaceReadme resource represents the readme file for a workspace. (for requests)
type WorkspaceReadmeRequest struct {
	ID         string                           `json:"id,omitempty"`
	Type       string                           `json:"type,omitempty"`
	Attributes WorkspaceReadmeAttributesRequest `json:"attributes,omitempty"`
}

// MarshalJSON automatically sets the Type field during marshalling
func (r WorkspaceReadmeRequest) MarshalJSON() ([]byte, error) {
	type Alias WorkspaceReadmeRequest
	if r.Type == "" {
		r.Type = "workspace-readme"
	}
	return json.Marshal((Alias)(r))
}

// GetID returns the resource ID (implements client.ResourceLike)
func (r WorkspaceReadmeRequest) GetID() string {
	return r.ID
}

// GetResourceType returns the JSON:API resource type (implements client.ResourceLike)
func (r WorkspaceReadmeRequest) GetResourceType() string {
	return "workspace-readme"
}

// WorkspaceReadmeAttributesRequest holds the attributes for WorkspaceReadme (request)
type WorkspaceReadmeAttributesRequest struct {
	// The content of the readme file.
	Content *value.Value[string] `json:"content,omitempty"`
	// The time when the readme record was created.
	CreatedAt *value.Value[time.Time] `json:"created-at,omitempty"`
}
