// Code generated by scalr-gen. DO NOT EDIT.

package billing_usage

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to BillingUsage operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new BillingUsage client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint returns billing usage statistics.
func (c *Client) ListBillingUsageRaw(ctx context.Context, opts *ListBillingUsageOptions) (*http.Response, error) {
	path := "/reports/billing"

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Format (string)
		if opts.Format != "" {
			params.Set("format", opts.Format)
		}
		// Handle parameter: BreakdownBy ([]string)
		// Complex type []string - skip for now
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint returns billing usage statistics.
func (c *Client) ListBillingUsage(ctx context.Context, opts *ListBillingUsageOptions) ([]*schemas.BillingUsage, *client.Response, error) {
	httpResp, err := c.ListBillingUsageRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.BillingUsage `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.BillingUsage, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListBillingUsageIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.BillingUsage.ListBillingUsageIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListBillingUsageIter(ctx context.Context, opts *ListBillingUsageOptions) iter.Seq2[schemas.BillingUsage, error] {
	return func(yield func(schemas.BillingUsage, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.BillingUsage{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListBillingUsageOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListBillingUsage(ctx, pageOpts)
			if err != nil {
				yield(schemas.BillingUsage{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListBillingUsagePaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.BillingUsage.ListBillingUsagePaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListBillingUsagePaged(ctx context.Context, opts *ListBillingUsageOptions) *client.Iterator[schemas.BillingUsage] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.BillingUsage, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListBillingUsageOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListBillingUsage(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.BillingUsage](ctx, pageSize, fetchPage)
}

// ListBillingUsageOptions holds optional parameters for ListBillingUsage
type ListBillingUsageOptions struct {
	// Format of the response. It can be 'json' or 'csv'.
	Format string
	// Breakdown by account, environment, workspace or both (comma-separated) If the parent control tower account breaks down by workspace and environment shows the values from current account.
	BreakdownBy []string
	// Search by workspace/environment name or ID.
	Query string
	// Page number.
	PageNumber int
	// Page size.
	PageSize int
	// The comma-separated list of attributes.
	Sort   []string
	Filter map[string]string
}
