// Code generated by scalr-gen. DO NOT EDIT.

package agent_pool_mtls_certificate

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to AgentPoolMTLSCertificate operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new AgentPoolMTLSCertificate client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Disables mTLS client certificate enforcement for the specified agent pool. Once disabled, agent sessions are no longer required to present a client certificate.
func (c *Client) DisableMtlsEnforcementRaw(ctx context.Context, agentPool string) (*client.Response, error) {
	path := "/agent-pools/{agent_pool}/actions/disable-mtls-enforcement"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Disables mTLS client certificate enforcement for the specified agent pool. Once disabled, agent sessions are no longer required to present a client certificate.
func (c *Client) DisableMtlsEnforcement(ctx context.Context, agentPool string) error {
	resp, err := c.DisableMtlsEnforcementRaw(ctx, agentPool)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// Once enabled, all agent sessions connecting to this pool must present a valid mTLS client certificate signed by the Scalr platform. Sessions without a verified certificate are rejected with “401 Unauthorized“.
func (c *Client) EnableMtlsEnforcementRaw(ctx context.Context, agentPool string) (*client.Response, error) {
	path := "/agent-pools/{agent_pool}/actions/enable-mtls-enforcement"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Once enabled, all agent sessions connecting to this pool must present a valid mTLS client certificate signed by the Scalr platform. Sessions without a verified certificate are rejected with “401 Unauthorized“.
func (c *Client) EnableMtlsEnforcement(ctx context.Context, agentPool string) error {
	resp, err := c.EnableMtlsEnforcementRaw(ctx, agentPool)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// Returns all mTLS certificates issued for the specified agent pool. Each certificate includes a computed “status“ field derived from its “is_active“ flag and “not_valid_after“ expiry.
func (c *Client) ListMtlsCertificatesRaw(ctx context.Context, agentPool string, opts *ListMtlsCertificatesOptions) (*client.Response, error) {
	path := "/agent-pools/{agent_pool}/mtls-certificates"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Returns all mTLS certificates issued for the specified agent pool. Each certificate includes a computed “status“ field derived from its “is_active“ flag and “not_valid_after“ expiry.
func (c *Client) ListMtlsCertificates(ctx context.Context, agentPool string, opts *ListMtlsCertificatesOptions) ([]*schemas.AgentPoolMTLSCertificate, error) {
	resp, err := c.ListMtlsCertificatesRaw(ctx, agentPool, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data []schemas.AgentPoolMTLSCertificate `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.AgentPoolMTLSCertificate, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	return resources, nil
}

// ListMtlsCertificatesIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.AgentPoolMTLSCertificate.ListMtlsCertificatesIter(ctx, agentPool, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListMtlsCertificatesIter(ctx context.Context, agentPool string, opts *ListMtlsCertificatesOptions) iter.Seq2[schemas.AgentPoolMTLSCertificate, error] {
	return func(yield func(schemas.AgentPoolMTLSCertificate, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.AgentPoolMTLSCertificate{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListMtlsCertificatesOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page using Raw method to get pagination metadata
			resp, err := c.ListMtlsCertificatesRaw(ctx, agentPool, pageOpts)
			if err != nil {
				yield(schemas.AgentPoolMTLSCertificate{}, err)
				return
			}
			defer resp.Body.Close()

			// Decode response
			var result struct {
				Data []schemas.AgentPoolMTLSCertificate `json:"data"`
				Meta struct {
					Pagination *client.Pagination `json:"pagination"`
				} `json:"meta"`
				Included []map[string]interface{} `json:"included"`
			}
			if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
				yield(schemas.AgentPoolMTLSCertificate{}, fmt.Errorf("failed to decode response: %w", err))
				return
			}

			// Yield each item
			for i := range result.Data {
				// Populate included resources into relationships
				if len(result.Included) > 0 {
					result.Data[i].Relationships.PopulateIncludes(result.Included)
				}
				if !yield(result.Data[i], nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if result.Meta.Pagination == nil || result.Meta.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListMtlsCertificatesPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.AgentPoolMTLSCertificate.ListMtlsCertificatesPaged(ctx, agentPool, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListMtlsCertificatesPaged(ctx context.Context, agentPool string, opts *ListMtlsCertificatesOptions) *client.Iterator[schemas.AgentPoolMTLSCertificate] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.AgentPoolMTLSCertificate, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListMtlsCertificatesOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the Raw method to get pagination metadata
		resp, err := c.ListMtlsCertificatesRaw(ctx, agentPool, pageOpts)
		if err != nil {
			return nil, nil, err
		}
		defer resp.Body.Close()

		// Decode response
		var result struct {
			Data []schemas.AgentPoolMTLSCertificate `json:"data"`
			Meta struct {
				Pagination *client.Pagination `json:"pagination"`
			} `json:"meta"`
			Included []map[string]interface{} `json:"included"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			return nil, nil, fmt.Errorf("failed to decode response: %w", err)
		}

		// Convert to slice of pointers and populate includes
		items := make([]*schemas.AgentPoolMTLSCertificate, len(result.Data))
		for i := range result.Data {
			items[i] = &result.Data[i]
			// Populate included resources into relationships
			if len(result.Included) > 0 {
				items[i].Relationships.PopulateIncludes(result.Included)
			}
		}

		return items, result.Meta.Pagination, nil
	}

	return client.NewIterator[schemas.AgentPoolMTLSCertificate](ctx, pageSize, fetchPage)
}

// ListMtlsCertificatesOptions holds optional parameters for ListMtlsCertificates
type ListMtlsCertificatesOptions struct {
	// Search certificates by partial SHA-256 fingerprint.
	Query string
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort   []string
	Filter map[string]string
}

// Revokes an mTLS certificate by deactivating it. Agents presenting this certificate will no longer be accepted when mTLS enforcement is enabled on the pool.
func (c *Client) RevokeMtlsCertificateRaw(ctx context.Context, agentPool string, certificateId string) (*client.Response, error) {
	path := "/agent-pools/{agent_pool}/mtls-certificates/{certificate_id}/actions/revoke"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))
	path = strings.ReplaceAll(path, "{certificate_id}", url.PathEscape(certificateId))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Revokes an mTLS certificate by deactivating it. Agents presenting this certificate will no longer be accepted when mTLS enforcement is enabled on the pool.
func (c *Client) RevokeMtlsCertificate(ctx context.Context, agentPool string, certificateId string) error {
	resp, err := c.RevokeMtlsCertificateRaw(ctx, agentPool, certificateId)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// This endpoint signs a CSR for an agent pool certificate to use it for agent mTLS connection. Example CSR generation with OpenSSL (EC P-256):: openssl ecparam -genkey -name prime256v1 -noout -out scalr-agent.key openssl req -new -key scalr-agent.key -out scalr-agent.csr -subj "/CN=agent-pool"
func (c *Client) SignCsrRaw(ctx context.Context, agentPool string, req *schemas.CertificateSigningRequest) (*client.Response, error) {
	path := "/agent-pools/{agent_pool}/actions/sign-csr"
	path = strings.ReplaceAll(path, "{agent_pool}", url.PathEscape(agentPool))

	// Plain JSON request (not JSON:API)
	headers := map[string]string{"Content-Type": "application/json"}
	httpResp, err := c.httpClient.Post(ctx, path, req, headers)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint signs a CSR for an agent pool certificate to use it for agent mTLS connection. Example CSR generation with OpenSSL (EC P-256):: openssl ecparam -genkey -name prime256v1 -noout -out scalr-agent.key openssl req -new -key scalr-agent.key -out scalr-agent.csr -subj "/CN=agent-pool"
func (c *Client) SignCsr(ctx context.Context, agentPool string, req *schemas.CertificateSigningRequest) (string, error) {
	resp, err := c.SignCsrRaw(ctx, agentPool, req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	bodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), nil
}
