// Code generated by scalr-gen. DO NOT EDIT.

package slack_integration

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to SlackIntegration operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new SlackIntegration client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint creates Slack integration.
func (c *Client) CreateSlackIntegrationRaw(ctx context.Context, req *schemas.SlackIntegrationRequest) (*http.Response, error) {
	path := "/integrations/slack"

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// This endpoint creates Slack integration.
func (c *Client) CreateSlackIntegration(ctx context.Context, req *schemas.SlackIntegrationRequest) (*schemas.SlackIntegration, *client.Response, error) {
	httpResp, err := c.CreateSlackIntegrationRaw(ctx, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.SlackIntegration `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// This endpoint deletes Slack integration.
func (c *Client) DeleteSlackIntegrationRaw(ctx context.Context, slackIntegration string) (*http.Response, error) {
	path := "/integrations/slack/{slack_integration}"
	path = strings.ReplaceAll(path, "{slack_integration}", url.PathEscape(slackIntegration))

	return c.httpClient.Delete(ctx, path, nil, nil)
}

// This endpoint deletes Slack integration.
func (c *Client) DeleteSlackIntegration(ctx context.Context, slackIntegration string) (*client.Response, error) {
	httpResp, err := c.DeleteSlackIntegrationRaw(ctx, slackIntegration)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Show details of a specific Slack integration.
func (c *Client) GetSlackIntegrationRaw(ctx context.Context, slackIntegration string, opts *GetSlackIntegrationOptions) (*http.Response, error) {
	path := "/integrations/slack/{slack_integration}"
	path = strings.ReplaceAll(path, "{slack_integration}", url.PathEscape(slackIntegration))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific Slack integration.
func (c *Client) GetSlackIntegration(ctx context.Context, slackIntegration string, opts *GetSlackIntegrationOptions) (*schemas.SlackIntegration, *client.Response, error) {
	httpResp, err := c.GetSlackIntegrationRaw(ctx, slackIntegration, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.SlackIntegration `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetSlackIntegrationOptions holds optional parameters for GetSlackIntegration
type GetSlackIntegrationOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint returns a list of Slack integrations.
func (c *Client) ListSlackIntegrationsRaw(ctx context.Context, opts *ListSlackIntegrationsOptions) (*http.Response, error) {
	path := "/integrations/slack"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint returns a list of Slack integrations.
func (c *Client) ListSlackIntegrations(ctx context.Context, opts *ListSlackIntegrationsOptions) ([]*schemas.SlackIntegration, *client.Response, error) {
	httpResp, err := c.ListSlackIntegrationsRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.SlackIntegration `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.SlackIntegration, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListSlackIntegrationsIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.SlackIntegration.ListSlackIntegrationsIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListSlackIntegrationsIter(ctx context.Context, opts *ListSlackIntegrationsOptions) iter.Seq2[schemas.SlackIntegration, error] {
	return func(yield func(schemas.SlackIntegration, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.SlackIntegration{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListSlackIntegrationsOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListSlackIntegrations(ctx, pageOpts)
			if err != nil {
				yield(schemas.SlackIntegration{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListSlackIntegrationsPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.SlackIntegration.ListSlackIntegrationsPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListSlackIntegrationsPaged(ctx context.Context, opts *ListSlackIntegrationsOptions) *client.Iterator[schemas.SlackIntegration] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.SlackIntegration, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListSlackIntegrationsOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListSlackIntegrations(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.SlackIntegration](ctx, pageSize, fetchPage)
}

// ListSlackIntegrationsOptions holds optional parameters for ListSlackIntegrations
type ListSlackIntegrationsOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of relationship paths.
	Include []string
	// The comma-separated list of attributes.
	Sort   []string
	Filter map[string]string
}

// This endpoint updates Slack integration.
func (c *Client) UpdateSlackIntegrationRaw(ctx context.Context, slackIntegration string, req *schemas.SlackIntegrationRequest) (*http.Response, error) {
	path := "/integrations/slack/{slack_integration}"
	path = strings.ReplaceAll(path, "{slack_integration}", url.PathEscape(slackIntegration))

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Patch(ctx, path, body, nil)
}

// This endpoint updates Slack integration.
func (c *Client) UpdateSlackIntegration(ctx context.Context, slackIntegration string, req *schemas.SlackIntegrationRequest) (*schemas.SlackIntegration, *client.Response, error) {
	httpResp, err := c.UpdateSlackIntegrationRaw(ctx, slackIntegration, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.SlackIntegration `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}
