// Code generated by scalr-gen. DO NOT EDIT.

package policy

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to Policy operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new Policy client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Show details of a specific OPA policy.
func (c *Client) GetPolicyRaw(ctx context.Context, policy string) (*client.Response, error) {
	path := "/policies/{policy}"
	path = strings.ReplaceAll(path, "{policy}", url.PathEscape(policy))

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Show details of a specific OPA policy.
func (c *Client) GetPolicy(ctx context.Context, policy string) (*schemas.Policy, error) {
	resp, err := c.GetPolicyRaw(ctx, policy)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.Policy           `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}
