// Code generated by scalr-gen. DO NOT EDIT.

package provider_configuration

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to ProviderConfiguration operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new ProviderConfiguration client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// Create a new Provider configuration.
func (c *Client) CreateProviderConfigurationRaw(ctx context.Context, req *schemas.ProviderConfigurationRequest) (*client.Response, error) {
	path := "/provider-configurations"

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	httpResp, err := c.httpClient.Post(ctx, path, body, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Create a new Provider configuration.
func (c *Client) CreateProviderConfiguration(ctx context.Context, req *schemas.ProviderConfigurationRequest) (*schemas.ProviderConfiguration, error) {
	resp, err := c.CreateProviderConfigurationRaw(ctx, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.ProviderConfiguration `json:"data"`
		Included []map[string]interface{}      `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}

// The endpoint deletes a Provider configuration by ID.
func (c *Client) DeleteProviderConfigurationRaw(ctx context.Context, providerConfiguration string) (*client.Response, error) {
	path := "/provider-configurations/{provider_configuration}"
	path = strings.ReplaceAll(path, "{provider_configuration}", url.PathEscape(providerConfiguration))

	httpResp, err := c.httpClient.Delete(ctx, path, nil, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// The endpoint deletes a Provider configuration by ID.
func (c *Client) DeleteProviderConfiguration(ctx context.Context, providerConfiguration string) error {
	resp, err := c.DeleteProviderConfigurationRaw(ctx, providerConfiguration)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// Show details of a specific Provider configuration.
func (c *Client) GetProviderConfigurationRaw(ctx context.Context, providerConfiguration string, opts *GetProviderConfigurationOptions) (*client.Response, error) {
	path := "/provider-configurations/{provider_configuration}"
	path = strings.ReplaceAll(path, "{provider_configuration}", url.PathEscape(providerConfiguration))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// Show details of a specific Provider configuration.
func (c *Client) GetProviderConfiguration(ctx context.Context, providerConfiguration string, opts *GetProviderConfigurationOptions) (*schemas.ProviderConfiguration, error) {
	resp, err := c.GetProviderConfigurationRaw(ctx, providerConfiguration, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.ProviderConfiguration `json:"data"`
		Included []map[string]interface{}      `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}

// GetProviderConfigurationOptions holds optional parameters for GetProviderConfiguration
type GetProviderConfigurationOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint returns a list of Provider configurations by various filters.
func (c *Client) ListProviderConfigurationsRaw(ctx context.Context, opts *ListProviderConfigurationsOptions) (*client.Response, error) {
	path := "/provider-configurations"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	httpResp, err := c.httpClient.Get(ctx, path, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint returns a list of Provider configurations by various filters.
func (c *Client) ListProviderConfigurations(ctx context.Context, opts *ListProviderConfigurationsOptions) ([]*schemas.ProviderConfiguration, error) {
	resp, err := c.ListProviderConfigurationsRaw(ctx, opts)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data []schemas.ProviderConfiguration `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.ProviderConfiguration, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	return resources, nil
}

// ListProviderConfigurationsIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.ProviderConfiguration.ListProviderConfigurationsIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListProviderConfigurationsIter(ctx context.Context, opts *ListProviderConfigurationsOptions) iter.Seq2[schemas.ProviderConfiguration, error] {
	return func(yield func(schemas.ProviderConfiguration, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.ProviderConfiguration{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListProviderConfigurationsOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page using Raw method to get pagination metadata
			resp, err := c.ListProviderConfigurationsRaw(ctx, pageOpts)
			if err != nil {
				yield(schemas.ProviderConfiguration{}, err)
				return
			}
			defer resp.Body.Close()

			// Decode response
			var result struct {
				Data []schemas.ProviderConfiguration `json:"data"`
				Meta struct {
					Pagination *client.Pagination `json:"pagination"`
				} `json:"meta"`
				Included []map[string]interface{} `json:"included"`
			}
			if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
				yield(schemas.ProviderConfiguration{}, fmt.Errorf("failed to decode response: %w", err))
				return
			}

			// Yield each item
			for i := range result.Data {
				// Populate included resources into relationships
				if len(result.Included) > 0 {
					result.Data[i].Relationships.PopulateIncludes(result.Included)
				}
				if !yield(result.Data[i], nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if result.Meta.Pagination == nil || result.Meta.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListProviderConfigurationsPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.ProviderConfiguration.ListProviderConfigurationsPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListProviderConfigurationsPaged(ctx context.Context, opts *ListProviderConfigurationsOptions) *client.Iterator[schemas.ProviderConfiguration] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.ProviderConfiguration, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListProviderConfigurationsOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the Raw method to get pagination metadata
		resp, err := c.ListProviderConfigurationsRaw(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}
		defer resp.Body.Close()

		// Decode response
		var result struct {
			Data []schemas.ProviderConfiguration `json:"data"`
			Meta struct {
				Pagination *client.Pagination `json:"pagination"`
			} `json:"meta"`
			Included []map[string]interface{} `json:"included"`
		}
		if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
			return nil, nil, fmt.Errorf("failed to decode response: %w", err)
		}

		// Convert to slice of pointers and populate includes
		items := make([]*schemas.ProviderConfiguration, len(result.Data))
		for i := range result.Data {
			items[i] = &result.Data[i]
			// Populate included resources into relationships
			if len(result.Included) > 0 {
				items[i].Relationships.PopulateIncludes(result.Included)
			}
		}

		return items, result.Meta.Pagination, nil
	}

	return client.NewIterator[schemas.ProviderConfiguration](ctx, pageSize, fetchPage)
}

// ListProviderConfigurationsOptions holds optional parameters for ListProviderConfigurations
type ListProviderConfigurationsOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// The comma-separated list of attributes.
	Sort []string
	// The comma-separated list of relationship paths.
	Include []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}

// This endpoint updates attributes of an existing Provider configuration.
func (c *Client) UpdateProviderConfigurationRaw(ctx context.Context, providerConfiguration string, req *schemas.ProviderConfigurationRequest) (*client.Response, error) {
	path := "/provider-configurations/{provider_configuration}"
	path = strings.ReplaceAll(path, "{provider_configuration}", url.PathEscape(providerConfiguration))

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	httpResp, err := c.httpClient.Patch(ctx, path, body, nil)
	if err != nil {
		return nil, err
	}
	return &client.Response{Response: httpResp}, nil
}

// This endpoint updates attributes of an existing Provider configuration.
func (c *Client) UpdateProviderConfiguration(ctx context.Context, providerConfiguration string, req *schemas.ProviderConfigurationRequest) (*schemas.ProviderConfiguration, error) {
	resp, err := c.UpdateProviderConfigurationRaw(ctx, providerConfiguration, req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var result struct {
		Data     schemas.ProviderConfiguration `json:"data"`
		Included []map[string]interface{}      `json:"included"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, nil
}
