// Code generated by scalr-gen. DO NOT EDIT.

package module

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to Module operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new Module client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint creates a Module from a VCS repository. The module's source code directory should follow the [standard module structure](https://www.terraform.io/docs/language/modules/develop/structure.html). Scalr extracts various meta information from the module's source: * It's important to provide each `variable` and `output` blocks with a meaningful descriptions, as they will be displayed in a Module and Workspace Variables pages for your internal users. * README or README.md file will be displayed on a Module page. * Nested modules from `modules/` directory will be searchable and available though the Registry just like top-level modules. Modules can be published on both `account` and `environment` scopes. If neither scope is specified in the request body, the module will be published in the same scope that the related `vcs-provider` is published.
func (c *Client) CreateModuleRaw(ctx context.Context, req *schemas.ModuleRequest) (*http.Response, error) {
	path := "/modules"

	// Wrap request in JSON:API envelope
	body := map[string]interface{}{"data": req}
	return c.httpClient.Post(ctx, path, body, nil)
}

// This endpoint creates a Module from a VCS repository. The module's source code directory should follow the [standard module structure](https://www.terraform.io/docs/language/modules/develop/structure.html). Scalr extracts various meta information from the module's source: * It's important to provide each `variable` and `output` blocks with a meaningful descriptions, as they will be displayed in a Module and Workspace Variables pages for your internal users. * README or README.md file will be displayed on a Module page. * Nested modules from `modules/` directory will be searchable and available though the Registry just like top-level modules. Modules can be published on both `account` and `environment` scopes. If neither scope is specified in the request body, the module will be published in the same scope that the related `vcs-provider` is published.
func (c *Client) CreateModule(ctx context.Context, req *schemas.ModuleRequest) (*schemas.Module, *client.Response, error) {
	httpResp, err := c.CreateModuleRaw(ctx, req)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.Module           `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// This endpoint removes the module from the registry.
func (c *Client) DeleteModuleRaw(ctx context.Context, module string) (*http.Response, error) {
	path := "/modules/{module}"
	path = strings.ReplaceAll(path, "{module}", url.PathEscape(module))

	return c.httpClient.Delete(ctx, path, nil, nil)
}

// This endpoint removes the module from the registry.
func (c *Client) DeleteModule(ctx context.Context, module string) (*client.Response, error) {
	httpResp, err := c.DeleteModuleRaw(ctx, module)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}

// Show details of a specific terraform module.
func (c *Client) GetModuleRaw(ctx context.Context, module string, opts *GetModuleOptions) (*http.Response, error) {
	path := "/modules/{module}"
	path = strings.ReplaceAll(path, "{module}", url.PathEscape(module))

	params := url.Values{}
	if opts != nil {
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// Show details of a specific terraform module.
func (c *Client) GetModule(ctx context.Context, module string, opts *GetModuleOptions) (*schemas.Module, *client.Response, error) {
	httpResp, err := c.GetModuleRaw(ctx, module, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data     schemas.Module           `json:"data"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	// Populate included resources into relationships
	if len(result.Included) > 0 {
		result.Data.Relationships.PopulateIncludes(result.Included)
	}
	return &result.Data, resp, nil
}

// GetModuleOptions holds optional parameters for GetModule
type GetModuleOptions struct {
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint lists modules by various filters. To list modules accessible from a certain environment, `filter[environment]` has to be specified. Modules from the account which this environment belongs as well as globally published modules will be listed as well. To list modules accessible from a certain account, `filter[account]` has to be specified. Modules published globally will be listed as well. To list modules accessible globally, both `filter[account]=null` and `filter[environment]=null` have to be specified. If no filters were specified, all modules which the user has read access to will be listed.
func (c *Client) ListModulesRaw(ctx context.Context, opts *ListModulesOptions) (*http.Response, error) {
	path := "/modules"

	params := url.Values{}
	if opts != nil {
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists modules by various filters. To list modules accessible from a certain environment, `filter[environment]` has to be specified. Modules from the account which this environment belongs as well as globally published modules will be listed as well. To list modules accessible from a certain account, `filter[account]` has to be specified. Modules published globally will be listed as well. To list modules accessible globally, both `filter[account]=null` and `filter[environment]=null` have to be specified. If no filters were specified, all modules which the user has read access to will be listed.
func (c *Client) ListModules(ctx context.Context, opts *ListModulesOptions) ([]*schemas.Module, *client.Response, error) {
	httpResp, err := c.ListModulesRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.Module `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.Module, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListModulesIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.Module.ListModulesIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListModulesIter(ctx context.Context, opts *ListModulesOptions) iter.Seq2[schemas.Module, error] {
	return func(yield func(schemas.Module, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.Module{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListModulesOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListModules(ctx, pageOpts)
			if err != nil {
				yield(schemas.Module{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListModulesPaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.Module.ListModulesPaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListModulesPaged(ctx context.Context, opts *ListModulesOptions) *client.Iterator[schemas.Module] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.Module, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListModulesOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListModules(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.Module](ctx, pageSize, fetchPage)
}

// ListModulesOptions holds optional parameters for ListModules
type ListModulesOptions struct {
	// Page number
	PageNumber int
	// Page size
	PageSize int
	// Query string, search by id, name, provider, and submodules recursively
	Query string
	// The comma-separated list of relationship paths.
	Include []string
	// The comma-separated list of attributes.
	Sort []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	Filter map[string]string
}

// Trigger resync of the Module associated with the VCS repository.
func (c *Client) ResyncModuleRaw(ctx context.Context, module string, req *schemas.ModuleResyncRequest) (*http.Response, error) {
	path := "/modules/{module}/actions/resync"
	path = strings.ReplaceAll(path, "{module}", url.PathEscape(module))

	// Plain JSON request (not JSON:API)
	headers := map[string]string{"Content-Type": "application/json"}
	return c.httpClient.Post(ctx, path, req, headers)
}

// Trigger resync of the Module associated with the VCS repository.
func (c *Client) ResyncModule(ctx context.Context, module string, req *schemas.ModuleResyncRequest) (*client.Response, error) {
	httpResp, err := c.ResyncModuleRaw(ctx, module, req)
	if err != nil {
		return nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	return resp, nil
}
