// Code generated by scalr-gen. DO NOT EDIT.

package terraform_module_version_usage

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"net/http"
	"net/url"
	"strings"

	"github.com/scalr/go-scalr/v2/scalr/client"
	"github.com/scalr/go-scalr/v2/scalr/schemas"
)

// Client provides access to TerraformModuleVersionUsage operations
type Client struct {
	httpClient *client.HTTPClient
}

// New creates a new TerraformModuleVersionUsage client
func New(httpClient *client.HTTPClient) *Client {
	return &Client{httpClient: httpClient}
}

// This endpoint lists terraform module usage.
func (c *Client) ListTerraformModuleUsageRaw(ctx context.Context, opts *ListTerraformModuleUsageOptions) (*http.Response, error) {
	path := "/reports/module-usage"

	params := url.Values{}
	if opts != nil {
		// Handle parameter: Query (string)
		if opts.Query != "" {
			params.Set("query", opts.Query)
		}
		if opts.PageNumber > 0 {
			params.Set("page[number]", fmt.Sprintf("%d", opts.PageNumber))
		}
		if opts.PageSize > 0 {
			params.Set("page[size]", fmt.Sprintf("%d", opts.PageSize))
		}
		// Handle parameter: Format (string)
		if opts.Format != "" {
			params.Set("format", opts.Format)
		}
		if len(opts.Sort) > 0 {
			params.Set("sort", strings.Join(opts.Sort, ","))
		}
		// Handle parameter: Fields (map[string]interface{})
		// Complex type map[string]interface{} - skip for now
		if len(opts.Include) > 0 {
			params.Set("include", strings.Join(opts.Include, ","))
		}
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists terraform module usage.
func (c *Client) ListTerraformModuleUsage(ctx context.Context, opts *ListTerraformModuleUsageOptions) ([]*schemas.TerraformModuleVersionUsage, *client.Response, error) {
	httpResp, err := c.ListTerraformModuleUsageRaw(ctx, opts)
	if err != nil {
		return nil, nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	var result struct {
		Data []schemas.TerraformModuleVersionUsage `json:"data"`
		Meta struct {
			Pagination *client.Pagination `json:"pagination"`
		} `json:"meta"`
		Included []map[string]interface{} `json:"included"`
	}
	if err := json.NewDecoder(httpResp.Body).Decode(&result); err != nil {
		return nil, resp, fmt.Errorf("failed to decode response: %w", err)
	}

	resources := make([]*schemas.TerraformModuleVersionUsage, len(result.Data))
	for i := range result.Data {
		resources[i] = &result.Data[i]
		// Populate included resources into relationships
		if len(result.Included) > 0 {
			resources[i].Relationships.PopulateIncludes(result.Included)
		}
	}
	resp.Pagination = result.Meta.Pagination
	return resources, resp, nil
}

// ListTerraformModuleUsageIter returns an iterator for paginated results using Go 1.23+ range over iter.Seq2 feature.
// This is the recommended and simple way to iterate through all the results.
//
// The iterator automatically fetches pages as needed and handles errors inline.
//
// Example:
//
//	for item, err := range client.TerraformModuleVersionUsage.ListTerraformModuleUsageIter(ctx, opts) {
//	    if err != nil {
//	        return err
//	    }
//	    // Process item
//	}
func (c *Client) ListTerraformModuleUsageIter(ctx context.Context, opts *ListTerraformModuleUsageOptions) iter.Seq2[schemas.TerraformModuleVersionUsage, error] {
	return func(yield func(schemas.TerraformModuleVersionUsage, error) bool) {
		// Determine page size from opts or use default
		pageSize := 20
		if opts != nil && opts.PageSize > 0 {
			pageSize = opts.PageSize
		}

		pageNum := 1

		for {
			// Check context
			if err := ctx.Err(); err != nil {
				yield(schemas.TerraformModuleVersionUsage{}, err)
				return
			}

			// Copy options and set page number
			pageOpts := &ListTerraformModuleUsageOptions{}
			if opts != nil {
				*pageOpts = *opts
			}
			pageOpts.PageNumber = pageNum
			pageOpts.PageSize = pageSize

			// Fetch page
			items, resp, err := c.ListTerraformModuleUsage(ctx, pageOpts)
			if err != nil {
				yield(schemas.TerraformModuleVersionUsage{}, err)
				return
			}

			// Yield each item
			for _, item := range items {
				if !yield(*item, nil) {
					return // Consumer requested early exit
				}
			}

			// Check if there are more pages
			if resp.Pagination == nil || resp.Pagination.NextPage == nil {
				break
			}

			pageNum++
		}
	}
}

// ListTerraformModuleUsagePaged returns a stateful iterator with access to pagination metadata.
// Use this when you need PageInfo(), Remaining(), or Collect() methods.
//
// Example:
//
//	iter := client.TerraformModuleVersionUsage.ListTerraformModuleUsagePaged(ctx, opts)
//	for iter.Next() {
//	    item := iter.Value()
//	    fmt.Print(iter.PageInfo()) // -> "page 2/5"
//	    fmt.Printf("%d items remaining", iter.Remaining())
//	}
//	if err := iter.Err(); err != nil {
//	    // Handle error
//	}
func (c *Client) ListTerraformModuleUsagePaged(ctx context.Context, opts *ListTerraformModuleUsageOptions) *client.Iterator[schemas.TerraformModuleVersionUsage] {
	// Determine page size from opts or use default
	pageSize := 20
	if opts != nil && opts.PageSize > 0 {
		pageSize = opts.PageSize
	}

	// Fetch function that will be called for each page
	fetchPage := func(ctx context.Context, pageNum int) ([]*schemas.TerraformModuleVersionUsage, *client.Pagination, error) {
		// Copy options and set page number
		pageOpts := &ListTerraformModuleUsageOptions{}
		if opts != nil {
			*pageOpts = *opts
		}
		pageOpts.PageNumber = pageNum
		pageOpts.PageSize = pageSize

		// Call the actual list method
		items, resp, err := c.ListTerraformModuleUsage(ctx, pageOpts)
		if err != nil {
			return nil, nil, err
		}

		return items, resp.Pagination, nil
	}

	return client.NewIterator[schemas.TerraformModuleVersionUsage](ctx, pageSize, fetchPage)
}

// ListTerraformModuleUsageOptions holds optional parameters for ListTerraformModuleUsage
type ListTerraformModuleUsageOptions struct {
	// The search string. Supports search by workspace name.
	Query string
	// Page number.
	PageNumber int
	// Page size.
	PageSize int
	// Format of the response. It can be 'json' or 'csv'.
	Format string
	// The comma-separated list of attributes.
	Sort []string
	// The value of the fields[resource-type] parameter is a comma-separated list that refers to the name of the fields to be returned for the resource. An empty value indicates that no fields should be returned.
	Fields map[string]interface{}
	// The comma-separated list of relationship paths.
	Include []string
	Filter  map[string]string
}

// This endpoint lists unique terraform module versions.
func (c *Client) ListTerraformModuleVersionsUsageRaw(ctx context.Context, opts *ListTerraformModuleVersionsUsageOptions) (*http.Response, error) {
	path := "/reports/module-versions-usage"

	params := url.Values{}
	if opts != nil {
		// Add filters
		for k, v := range opts.Filter {
			params.Set("filter["+k+"]", v)
		}
	}
	if len(params) > 0 {
		path += "?" + params.Encode()
	}

	return c.httpClient.Get(ctx, path, nil)
}

// This endpoint lists unique terraform module versions.
func (c *Client) ListTerraformModuleVersionsUsage(ctx context.Context, opts *ListTerraformModuleVersionsUsageOptions) (string, *client.Response, error) {
	httpResp, err := c.ListTerraformModuleVersionsUsageRaw(ctx, opts)
	if err != nil {
		return "", nil, err
	}
	defer httpResp.Body.Close()

	resp := &client.Response{Response: httpResp}

	bodyBytes, err := io.ReadAll(httpResp.Body)
	if err != nil {
		return "", resp, fmt.Errorf("failed to read response body: %w", err)
	}
	return string(bodyBytes), resp, nil
}

// ListTerraformModuleVersionsUsageOptions holds optional parameters for ListTerraformModuleVersionsUsage
type ListTerraformModuleVersionsUsageOptions struct {
	Filter map[string]string
}
