name: default

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
  tests:
    runs-on: ubuntu-latest
    name: tests
    env:
      REVIZOR_URL: ${{ secrets.REVIZOR_URL }}
      REVIZOR_TOKEN: ${{ secrets.REVIZOR_TOKEN }}
      SCALR_TOKEN: ${{ secrets.SCALR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Set API_BRANCH
        if: ${{ contains(github.event.head_commit.message, '[API_BRANCH]') }}
        run: echo "API_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Set DB_BRANCH
        if: ${{ contains(github.event.head_commit.message, '[DB_BRANCH]') }}
        run: echo "DB_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      - name: Create container
        id: create
        uses: Scalr/gh-action-revizor@master
        with:
          command: create
      - name: Run tests
        env:
          SCALR_ADDRESS: https://${{ steps.create.outputs.hostname }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github
      - name: Delete container
        id: delete
        if: ${{ always() && steps.create.outputs.container_id }}
        uses: Scalr/gh-action-revizor@master
        with:
          command: delete
          container_id: ${{ steps.create.outputs.container_id }}
